aws-samples/pcluster-manager

README.md, scripts/update.sh
* Allows for updating without editing the region param in the update script
```
./update.sh us-east-1
```
=> Change Update script

api/PclusterApiHandler.py, app.py, frontend/src/model.js, frontend/src/pages/Clusters/ClusterActions.js, frontend/src/pages/Clusters/ClusterInstances.js, frontend/src/pages/Clusters/ClusterProperties.js, infrastructure/pcluster-manager.yaml
=> `[Clusters]` Add support for stopping / starting head node.

frontend/src/pages/Configure/Create.js, frontend/src/pages/Configure/Queues.js, frontend/src/pages/Configure/Source.js, frontend/src/pages/Configure/Storage.js, frontend/src/pages/Configure/WizardDialog.js, frontend/src/pages/Configure/util.js, frontend/src/util.js
=> [config] Better handling of templates loading.

frontend/src/pages/Clusters/ClusterActions.js, frontend/src/pages/Configure/HeadNode.js, frontend/src/pages/Configure/Storage.js
=> `[ClusterActions]` Add support for a filesystem button.

api/PclusterApiHandler.py, app.py, frontend/src/model.js, infrastructure/pcluster-manager.yaml
=> [api] Add support for determining the version from the CFN template.

api/PclusterApiHandler.py, frontend/src/pages/Configure/Queues.js
=> [api] Get efa_instance_types from the api.

frontend/src/pages/Clusters/ClusterDetails.js, frontend/src/pages/Configure/Cluster.js, frontend/src/pages/Configure/Components.js, frontend/src/pages/Configure/HeadNode.js, frontend/src/pages/Configure/Queues.js, frontend/src/pages/Configure/WizardDialog.js, frontend/src/store.js, frontend/src/util.js
=> `[Config/CustomActions]` Add support for CustomActions advanced option.

frontend/src/pages/Clusters/ClusterActions.js, frontend/src/pages/Configure/Cluster.js, frontend/src/pages/Configure/MultiUser.js, frontend/src/pages/Configure/WizardDialog.js, frontend/src/pages/Configure/util.js
=> `[MultiUser]` Add support for AD integration for API >= 3.1

infrastructure/pcluster-manager-cognito.yaml
=> `[infrastructure/cognito]` Support gov cloud auth.

frontend/src/pages/Configure/Cluster.js, frontend/src/pages/Configure/HeadNode.js
=> `[Configure/HeadNode/Keypair]` Allow selecting of None for keypair.

frontend/src/pages/Clusters/ClusterProperties.js
=> `[ClusterProperties]` Add mssh command.

frontend/src/model.js, frontend/src/pages/Configure/Create.js, frontend/src/pages/Configure/Queues.js
=> `[Configure/Update]` Add ability to force update when editing cluster config

api/PclusterApiHandler.py, app.py, frontend/src/model.js, frontend/src/pages/Clusters/ClusterScheduling.js, frontend/src/pages/Clusters/JobSubmitDialog.js
=> `[scheduling]` Add SubmitJob dialog.

frontend/src/pages/Clusters/ClusterScheduling.js, frontend/src/pages/Configure/Cluster.js
=> [pages] More nil punning to help when data isn't loaded yet.

scripts/update.sh
=> `[scripts/update]` Parameterize the tag for the update script.

infrastructure/upload-gov-cloud.sh, scripts/build_awslambda.sh, scripts/update.sh
=> Improve release

frontend/src/pages/Configure/Queues.js
*Issue #, if available:* 35
*Description of changes:* updat ethe queuesPath for capacityTypePath variable
=> Update queues path in capacityTypePath variable

infrastructure/pcluster-manager.yaml
=> Add Cognito Permissions

api/PclusterApiHandler.py, frontend/src/model.js, frontend/src/pages/Users/Users.js
=> Fix arg for delete user

frontend/src/pages/Users/Users.js
=> Disable deleting your user

frontend/src/pages/Configure/Queues.js
=> `[Configure/Queues]` Factor out default instance type.

frontend/src/pages/Configure/HeadNode.js
=> `[Configure/HeadNode]` Fix clearing of Imds > Secured when toggled off.

api/PclusterApiHandler.py, frontend/src/model.js, frontend/src/pages/Clusters/JobSubmitDialog.js
=> `[Scheduling/Submit]` Show submission errors to user.

api/PclusterApiHandler.py, frontend/src/components/TopBar.js, frontend/src/model.js, frontend/src/pages/Clusters/JobSubmitDialog.js
=> `[GovCloud/RegionSelect]` Limit to GovCloud region only

api/PclusterApiHandler.py, frontend/src/pages/Configure/HeadNode.js, infrastructure/pcluster-manager.yaml
=> Additional security groups

frontend/src/App.css, frontend/src/App.js, frontend/src/pages/Clusters/Actions.js, frontend/src/pages/Clusters/Clusters.js, frontend/src/pages/Configure/Cluster.js, frontend/src/pages/Configure/Components.js, frontend/src/pages/Configure/Configure.js, frontend/src/pages/Configure/Create.js, frontend/src/pages/Configure/HeadNode.js, frontend/src/pages/Configure/MultiUser.js, frontend/src/pages/Configure/Queues.js, frontend/src/pages/Configure/Source.js, frontend/src/pages/Configure/Storage.js, frontend/src/store.js
=> `[Configure]` Switch to non-modal configure flow.

frontend/src/pages/Configure/Configure.js
=> `[Configure]` Minimum width on modal.

frontend/src/pages/Configure/Components.js
=> G5 Instances

frontend/src/pages/Clusters/Logs.js
=> Logs Help Tooltip

frontend/src/App.css, frontend/src/pages/CustomImages/ImageBuildDialog.js
=> Switch to code editor

frontend/src/pages/Clusters/Logs.js
=> `[Logs]` Use a table to allow searching.

frontend/src/components/Status.js, frontend/src/pages/Clusters/Clusters.js, frontend/src/pages/Clusters/Instances.js, frontend/src/pages/Clusters/Properties.js
=> FAILED Tooltip

frontend/src/pages/Configure/Configure.js
=> Adjust Modal Size

frontend/package.json, frontend/src/App.css, frontend/src/App.js, frontend/src/components/ConfigView.js, frontend/src/components/SideBar.js, frontend/src/components/Status.js, frontend/src/pages/Clusters/Actions.js, frontend/src/pages/Clusters/Clusters.js, frontend/src/pages/Clusters/Details.js, frontend/src/pages/Clusters/Instances.js, frontend/src/pages/Clusters/Logs.js, frontend/src/pages/Clusters/Properties.js, frontend/src/pages/Clusters/StackEvents.js, frontend/src/pages/Clusters/util.js, frontend/src/pages/Configure/Cluster.js, frontend/src/pages/Configure/Components.js, frontend/src/pages/Configure/Configure.js, frontend/src/pages/Configure/Create.js, frontend/src/pages/Configure/MultiUser.js, frontend/src/pages/CustomImages/CustomImageDetails.js, frontend/src/pages/CustomImages/CustomImages.js, frontend/src/pages/Home/Home.js, frontend/src/pages/Layout.js, frontend/src/pages/OfficialImages/OfficialImages.js, frontend/src/pages/Users/Users.js, frontend/src/store.js
=> `[Routing]` Add support for routing to top-level pages.

api/PclusterApiHandler.py, app.py, frontend/src/model.js, frontend/src/pages/Configure/Components.js
=> `[instance-types]` Retrieve instances types from backend.

frontend/src/pages/Configure/Components.js
=> `[InstanceGroups]` Add r* and c6g to new instance groups.

README.md, frontend/src/components/TopBar.js
=> `[Naming]` Spell out ParallelCluster.

frontend/src/pages/Clusters/Clusters.js, frontend/src/pages/Configure/Components.js, resources/scripts/cloud9.sh, resources/scripts/multi-runner.py, resources/scripts/spack.sh
=> `[MultiRunner]` add support for running multiple post-install scripts.

frontend/src/pages/Clusters/JobSubmitDialog.js
=> `[JobSubmit]` Use an alert for the experimental node.

api/PclusterApiHandler.py, app.py, frontend/package.json, frontend/public/index.html, frontend/src/App.js, frontend/src/model.js, frontend/src/pages/Clusters/util.js, frontend/src/pages/Configure/Components.js, scripts/build_awslambda.sh
=> `[routing]` Update routing on backend server.

api/PclusterApiHandler.py, scripts/build.sh, scripts/update.sh
=> `[scripts/update]` Allow updating from local dev to private ecr.

infrastructure/pcluster-manager.yaml
=> Allow empty Subnet & VPC

frontend/src/pages/Configure/HeadNode.js
=> `[Configure/HeadNode]` Validate RootVolume size.

frontend/src/pages/OfficialImages/OfficialImages.js
*Issue #94
Update the fields for sorting columns on the OfficialImages pages.
Fixes #94 
=> `[OfficialImages]` Fix sorting on table columns.

frontend/src/model.js, frontend/src/pages/Configure/Create.js
*Issue #101 , if available:*
Fixes #101 
=> `[Create/disableRollback]` Add support for disabling rollback.

docs/static/02-tutorials/slurm-accounting/cfn-templates/accounting-cluster-template.yaml
This will make the guide much simpler.
=> Create Secrets Manager Role in CFN

frontend/src/pages/Configure/Configure.js
=> `[Edit/StopDialog]` Include a StopDialog component when editing.

infrastructure/pcluster-manager.yaml
=> `[Infrastructure/Policy]` Combine policy further.

frontend/src/pages/Configure/HeadNode.js
=> `[Configure/DCV]` Fix keys where we edit DCV settings.

infrastructure/pcluster-manager.yaml
=> Bump pcluster to 3.1.3

api/PclusterApiHandler.py
Fixes https://github.com/aws-samples/pcluster-manager/issues/135
=> Add t3 instances

frontend/src/pages/Users/Users.js
This solves https://github.com/aws-samples/pcluster-manager/issues/124
=> Email Validation

frontend/src/pages/Users/Users.js
=> User Role Tooltip

frontend/src/pages/Configure/Components.js, frontend/src/pages/Configure/HeadNode.js, frontend/src/pages/Configure/Queues.js
=> `[Configure/Queues]` Add ability to add IAM policies.

frontend/src/pages/Configure/Configure.js
=> `[Configure]` Fix the StopComputeFleet dialog.

frontend/src/pages/Configure/Queues.js
https://user-images.githubusercontent.com/5545980/172480455-da3db737-f55b-4146-a276-81f933a2e706.mov
=> EFA Default

README.md
Update instructions in README to add step for installing dependencies.
=> Added dependencies installation to README instructions

docs/content/02-tutorials/02-slurm-accounting.md
=> [docs] Fix typo

decisions/20220713-use-github-actions-for-pipelines.md
**Description of changes**
add an ADR to keep track of the Github Actions usage
**Testing**
Run log4brains in preview mode to see the changes
=> Add ADR for Github actions

docs/config.toml
=> New Domain / Amplify Hosting

infrastructure/upload-gov-cloud.sh, infrastructure/upload.sh
Use --region flag when uploading the templates to S3
Run the `update.sh` script.
=> Use --region flag when uploading the templates to S3

README.md
This patch adds missing parts to the local setup section fo the README.
=> Add missing parts in local setup section of the README

app.py
Disable authentication on non-API paths.
Manual test visiting index page.
=> Disable authentication on non-API paths

frontend/locales/en/strings.json, frontend/src/old-pages/Configure/Cluster.tsx, frontend/src/old-pages/Configure/Components.tsx, frontend/src/old-pages/Configure/Create.tsx, frontend/src/old-pages/Configure/HeadNode.tsx, frontend/src/old-pages/Configure/Queues.tsx, frontend/src/old-pages/Configure/Source.tsx, frontend/src/old-pages/Configure/Storage.tsx
Convert most of the prose in Wizard to use i18n
Manually walking through the wizard and looking at most of the UI
=> `[Wizard/i18n]` Convert more of the wizard to support i18n.

.github/workflows/pull_request.yml, frontend/package.json
This PR introduces linting and type checking in our pull_request workflow
- add `ts-validate` script
- run `lint` and `ts-validate` on PR
- Run commands manually
- This very PR is failing as there are type errors
=> Add linting and type checks to CI

frontend/src/old-pages/Configure/HeadNode.tsx
Remove `useTranslation` line that breaks wizard toggle.
Manual test with local setup.
=> Remove useTranslation line that breaks wizard toggle

app.py, frontend/src/model.tsx, infrastructure/pcluster-manager.yaml, scripts/build_awslambda.sh
We found some issues when releasing PCM 3.2.0. This is a PR to address all the issues.
See the commits list for details.
This has been tested locally trying a dry run
=> Fix release issues

.github/pull_request_template.md
This PR expands our pull_request_template with the following:
- a changelog section to allow PR authors to specify how their changes should be listed in the next releases' changelog
- a PR quality section to help PR authors make sure everything is order before submitting a PR
- update `pull_request_template.md`
N/A
=> Update PR template with a quality checklist

.github/workflows/demo_deploy.yml, scripts/update.sh
This PR adds to the `deploy_demo` workflow the following steps:
- FE and BE tests
- build and deploy the latest changes to the private demo environment
- Edit `update.sh` so that it doesn't depend on Python to be available
- Edit `deploy_demo.yml` to run `update.sh` on merge on `main`
- Successful run [here](https://github.com/aws-samples/pcluster-manager/runs/7884330921?check_suite_focus=true)
=> Deploy to Demo workflow

frontend/src/old-pages/Configure/Components.tsx
Make it easierfor user to actually find the scripts.
=> Update link to post-install scripts

scripts/update.sh
To prevent any potential leak of information from the Lambda it's better to suppress the output of the deploy command.
- suppressed the output of the `update-function-code` command
=> Silence update-lambda command

scripts/update.sh
Up until now the`update.sh` script works correctly only if the account has only one PCM deployed in the specified region.
This PR aims at providing the ability to select a specific stack to update with the latest version of PCM.
This is done through a new mandatory parameter to pass which is `--stack-name STACKNAME`.
Providing a stack name allows the script to retrieve the exact name of the lambda function to get the ARN for (belonging to the specified stack), so that the update action doesn't make any assumption of name prefix.
Plus, the private repo to update il also the one belonging the correct stack (specified through the new parameter of the script).
Our internal update process now allows (and correctly handles) multiple PCluster Manager deployments in a single account.
Since no …
=> Allow update.sh to update multiple stacks

.github/workflows/demo_deploy.yml
This PR adds an `update-infrastructure` step to the `demo_deploy.yml` workflow. 
- run `./infrastructure/update-environment-infra.sh demo` on merge
- add step to our merge workflow to update the infrastructure of the demo environment on merge
- Successful run https://github.com/aws-samples/pcluster-manager/actions/runs/3060894578
=> Add workflow to update infrastructure of private demo environment

infrastructure/github-env-setup.yml
Added iam:PassRole and lambda:UpdateFunctionConfiguration to fix depl…
UpdateInfrastructurePolicy
- adds iam:PassRole
- adds: lambda:UpdateFunctionConfiguration
Tested on the demo environment.
- #304
=> Fixed demo template after PR 304

infrastructure/pcluster-manager.yaml
Reverts aws-samples/pcluster-manager#307
=> Revert "Add parameters to support Okta"

PROJECT_GUIDELINES.md, infrastructure/pcluster-manager.yaml, scripts/build.sh, scripts/build_awslambda.sh, scripts/run.sh, scripts/update.sh
This PR introduces the use of the newly created public ECR registry, to be used for PCM distribution and release.
This PR should not be merged right away, but we can wait till release time to merge it.
The ECR repo has been manually tested to prove only the owner can push images to the repo.
=> Use team owned public repo

.github/workflows/production_release.yml, infrastructure/bucket_configuration.sh, infrastructure/github-env-setup-prod.yml, infrastructure/release_infrastructure.sh, infrastructure/slurm-accounting/upload.sh, infrastructure/upload.sh
This is the first version of the workflow used to release PCM to our customers.
- remove backup logic from release scripts which is not needed since those files are discarded automatically at the end of the run
- new IAM role to deploy to our public ECR registry
- added a new workflow, mimicking what we have done manually to release in production
Deployed to the new buckets/registry using a custom branch. [The triggered run](https://github.com/aws-samples/pcluster-manager/actions/runs/3235521704) has completed successfully, and the released file have been deployed with a 1-click CFN. The product is working correctly.
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the …
=> Production deploy workflow

docs/content/02-tutorials/01-setup-sms.md
Fixed typo that misspelled password. 
Typo
Typo fixed
Not required, just the documentation page. 
None
=> Fixed typo on page

docs/content/02-tutorials/02-slurm-accounting.md, docs/content/02-tutorials/03-memory-scheduling.md, docs/content/02-tutorials/04-cost-tracking.md, docs/content/02-tutorials/05-cloud9.md, docs/content/02-tutorials/06-downloading.md, docs/static/02-tutorials/slurm-accounting/pcluster/cluster-config.yaml.template
Public documentation update for upcoming release with support to Flexible Instance Types.
=> Update doc for Flexible Instance types

decisions/20221027-support-multiple-versions-of-pc-api.md
This PR adds an ADR describing our decision of using feature flags as a mechanism to more easily support multiple PC versions (implemented here #311 and here #315)
- add the adr to our decisions
=> Add ADR for feature flags

decisions/20221027-export-pcluster-manager-logs-from-cloudwatch.md
This PR adds an ADR describing our decision on how we let customers download PCM log archives.
New entry in the decisions folder
=> Add ADR for Log Export

infrastructure/environments/demo-cfn.yaml, infrastructure/pcluster-manager.yaml
Performed version bump to 3.3.0 for PC and PCM.
=> Bump PC and PCM version 3.3.0

.github/release.yml
Improved the `release.yml` to groups PRs based on new labels created for release purposes.
#351 
=> Added labels for grouping PRs after the ADR about automatic changelog creation

.github/pull_request_template.md
Added entry about logging best practices in PR template, with link and a couple of examples.
- [OWASP Logging](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html)
=> Added entry about logging best practices in PR template

.github/release.yml
Add `release:breaking-change` to the Changelog generation config file
=> Add `release:breaking-change` to the Changelog generation config file

frontend/locales/en/strings.json, frontend/src/components/ErrorBoundary.tsx, frontend/src/components/__tests__/ErrorBoundary.test.tsx, frontend/src/pages/_app.tsx
Currently in the frontend we don't have a global exception handler that catches all uncaught errors. In this way,
we risk breaking the whole app by not catching an error, and we cannot investigate the root cause since we are not logging anything.
This PR aims at solving this issue, by introducing an `ErrorBoundary` component which serves as a global exception handler for the frontend application. The component provides a way to gracefully handle internal errors occurring in children components, by rendering a fallback ui with a modal displaying an error message (see Screenshots section).
Furthermore, since Error boundaries do not catch errors for event handlers and asynchronous calls, we managed to add two event listeners to `window` for the following events:
* …
=> Introduce ErrorBoundary component which serves as a global exception handler for the frontend

.github/workflows/demo_deploy.yml
Update reference in CI workflow after recreating the Role
=> Update PrivateInfrastructureUpdate role arn

decisions/20221206-frontend-log-instrumentation.md
Just an ADR for how to instrument frontend code with logs to make up for the lack of source maps.
=> ADR for how to instrument the frontend with logs

docs/content/02-tutorials/01-setup-mfa.md, docs/content/02-tutorials/07-setup-iam.md
Add in documentation as a workaround for https://github.com/aws-samples/pcluster-manager/issues/384
N/A
=> IAM Policies Fix

api/PclusterApiHandler.py, app.py, frontend/locales/en/strings.json, frontend/src/components/Status.tsx, frontend/src/model.tsx, frontend/src/old-pages/Clusters/Accounting.tsx, frontend/src/old-pages/Clusters/Details.tsx, frontend/src/old-pages/Clusters/JobSubmitDialog.tsx, frontend/src/old-pages/Clusters/Scheduling.tsx, frontend/src/old-pages/Clusters/__tests__/util.test.ts, frontend/src/old-pages/Clusters/util.tsx, frontend/src/old-pages/Configure/Components.tsx, frontend/src/types/jobs.tsx, infrastructure/pcluster-manager.yaml, infrastructure/slurm-accounting/accounting-cluster-template.yaml, infrastructure/slurm-accounting/upload.sh, resources/files/sacct/slurm_accounting.rb, resources/files/sacct/slurm_sacct.conf.erb, resources/files/sacct/slurmdbd.conf.erb, resources/files/sacct/slurmdbd.service, resources/scripts/slurm-accounting.sh
Reverts aws-samples/pcluster-manager#411
=> Revert "Remove job scheduling and accounting info"

infrastructure/environments/demo-cfn.yaml, infrastructure/pcluster-manager.yaml
Updates the default version of PC installed to 3.4.0
Manually updated the demo environment and created a cluster
=> Update to PC 3.4.0

frontend/resources/attributions/npm-python-attributions.txt, resources/attributions/docker-attributions.txt
* Updated `docker-attributions.txt`
* Updated `npm-python-attributions.txt`
=> Update attributions doc

api/exception/handlers.py, api/tests/exceptions/test_exception_handlers.py
Changed description returned by the boto3 handler and adjusted tests accordingly.
- manually
- unit test
- e2e
=> Avoid boto3 exception details leakage

infrastructure/pcluster-manager.yaml
Added default values for new parameters from #456 
- added default parameter values for newly introduced parameters
=> Demo env fix: added default values for new parameters from PR #456

infrastructure/environments/demo-cfn.yaml
Passes new Cognito parameters to the demo env update, after deploying a standalone Cognito.
=> Fix updates to the demo env

api/PclusterApiHandler.py, api/exception/handlers.py, api/tests/exceptions/test_exception_handlers.py
This PR aim at adopting new exception handlers mechanism avoiding hardcoded 500 returned from service operations
- adoption of exception handlers for old methods
- adjusted tests
- manually
- unit
- e2e
=> Removed hardcoded 500 http return code

DEVELOPMENT.md, README.md
- move development guide into a separate readme
- add a guide to retrieve both the PC and PCM version from a CFN stack
- remove architecture and screenshots page
=> Align readme to the current project status and add troubleshooting info

api/exception/handlers.py, api/tests/conftest.py, api/tests/exceptions/test_exception_handlers.py, api/tests/validation/test_api_validation.py, api/validation/__init__.py, api/validation/schemas.py, api/validation/validators.py, app.py, requirements.txt
Added API input validation mechanism + decorator to validate API invocation at the controller level.
- added Marshmallow dependency to `requirements.txt`
- implemented new error handler for validation errors
- implemented validation mechanism + decorator
- provided three schemas with additional validation and adopted the new decorator on their respective endpoints
- added tests for all new code
- unit tests
- e2e tests
- manually
- postman
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> Added API signature validation

api/PclusterApiHandler.py, api/logging/__init__.py, api/tests/test_pcluster_api_handler.py, api/tests/test_push_log.py, api/validation/schemas.py, api/validation/validators.py, app.py
This PR introduces custom validators for the following endpoints:
- `/logs`
- `/login`
- `/manager/price_estimate`
Added input validators for the following endpoints: push_log, login, price_estimate
Manually
=> Added validation for endpoints: push_log, login, price_estimate

api/PclusterApiHandler.py, awslambda/serverless_wsgi.py
Removed print statements from the codebase.
Left them in the infrastructure file since they could be useful there.
=> Removed print statements from the codebase

frontend/resources/attributions/npm-python-attributions.txt, resources/attributions/docker-attributions.txt
* Updated `docker-attributions.txt`
* Updated `npm-python-attributions.txt`
=> Update attribution docs

frontend/next.config.js
Fixes https://github.com/aws-samples/pcluster-manager/actions/runs/3958972674
=> Override Next.js config to allow images inside an exported instance

e2e/specs/wizard.spec.ts, e2e/specs/wizard.template.spec.ts, frontend/locales/en/strings.json, frontend/src/old-pages/Clusters/__tests__/Clusters.test.tsx
This PR on top of #501, with fixes to make the frontend build pass.
Closes #501 .
=> Copywriting fixes

.github/workflows/demo_deploy.yml, infrastructure/environments/demo-cfn.yaml, infrastructure/environments/demo-variables.sh, infrastructure/github-env-setup.yml, infrastructure/parallelcluster-ui.yaml
Following https://github.com/aws-samples/pcluster-manager/pull/499, this PR updates old references to reflect product renaming in both GitHub workflows and Cfn templates.
* Manually deployed stacks in test account and emulated workflows
=> Update references to reflect product renaming in workflows and Cfn templates

infrastructure/github-env-setup.yml
This PR updates the GitHub env CFN template so that it allows the assuming Role to act on the correct ECR repository
- [successful run](https://github.com/aws-samples/pcluster-manager/actions/runs/3998568447/jobs/6863994748)
=> Update Policy to allow actions on the correct resource

infrastructure/parallelcluster-ui-cognito.yaml
Improved invite message template and removed verification mail settings from CloudFormation cognito template
- manually
=> Improved invite message template and removed verification mail settings from CloudFormation cognito template

frontend/locales/en/strings.json, frontend/src/old-pages/Clusters/Actions.tsx, frontend/src/old-pages/Users/Users.tsx
This PR updates copy of Users page, and adds hardcoded strings to our localization file
- manually
=> Update copy of Users page

frontend/locales/en/strings.json, frontend/src/old-pages/OfficialImages/OfficialImages.tsx
This PR updates copy of Official images page, and adds hardcoded strings to our localization file
- manually
=> Update copy of Official images page

e2e/configs/environment.ts
=> Updated e2e target endpoint

frontend/locales/en/strings.json, frontend/src/components/FileChooser.tsx, frontend/src/components/Loading.tsx, frontend/src/components/ValueWithLabel.tsx, frontend/src/old-pages/Clusters/Clusters.tsx, frontend/src/old-pages/Clusters/Properties.tsx, frontend/src/old-pages/CustomImages/CustomImageDetails.tsx, frontend/src/old-pages/CustomImages/CustomImageStackEvents.tsx, frontend/src/old-pages/CustomImages/CustomImages.tsx, frontend/src/old-pages/CustomImages/ImageBuildDialog.tsx
This PR updates copy of Custom images page, and adds hardcoded strings to our localization file
- manually
=> Update copy of Custom images page

infrastructure/parallelcluster-ui.yaml
Removed EcrRecipeVersion and explicited the expected format for PCUI versions
- manually, deploying a new PC UI instance in my account
- #514 
=> Removed EcrRecipeVersion and explicited the expected format for PCUI versions

e2e/specs/wizard.spec.ts
Fix e2e test after #531 
- #531 
=> Fixed e2e test

e2e/specs/wizard.spec.ts, frontend/locales/en/strings.json, frontend/src/old-pages/Configure/Configure.tsx, frontend/src/old-pages/Configure/Source.tsx
Adjusted source step after the rest of the wizard
- manually
- e2e
=> Adjusted source step after the rest of the wizard

.github/workflows/demo_deploy.yml, .github/workflows/e2e_tests.yml, .github/workflows/production_release.yml, infrastructure/README.md, infrastructure/environments/demo-cfn-update-args.yaml, infrastructure/environments/demo-variables.sh, infrastructure/github-env-setup-prod.yml, infrastructure/github-env-setup.yml, infrastructure/update-environment-infra.sh
Removes all sensitive info regarding AWS account ids and private S3 bucket names.
In gh action workflows leverages gh secrets to provide the IAM roles to assume for:
- ACTION_E2E_TESTS_ROLE
- ACTION_DEMO_DEPLOY_JOB_UPDATE_INFRASTRUCTURE_ROLE
- ACTION_DEMO_DEPLOY_JOB_BUILD_AND_DEPLOY_ROLE
- ACTION_PRODUCTION_RELEASE_ROLE
Still supports local infra updates, using a cloudformation resource lookup to find the infra s3 bucket based on the `pcluster-manager-github` cf stack name.
Infra docs updates.
Ensure sensitive information is retrieved via GitHub Secrets.
Tested
- e2e test
- demo deploy
I was unable to test the production release pipeline, it's a simple variable substitution and creating a whole env for it was not worth the effort.
In order to increase the likelihood of your contribution …
=> Remove sensitive info
