resources/scripts/spack.sh

This will give root control over common packages in /shared_dir, while individual users can have control in their home directory. Users get benefit of self-installed and upstream provided packages.

Added better UX for Spack

---

frontend/src/pages/Clusters/Actions.js
frontend/src/pages/Clusters/Scheduling.js

*Issue #125, if available:*
Guard around enabling SSM for the scheduling tab.

`[Cluster/Scheduling]` Guard around SSM for enabling the scheduling tab.

---

frontend/src/pages/Configure/Components.js
resources/scripts/mem.sh

All credit goes to @bollig
You'll also need the following IAM Policy in your cluster's config, this is for `ec2:DescribeInstanceTypes` to get the memory per-instance.
```yaml
Iam:
AdditionalIamPolicies:
- Policy: arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
```

Memory Post-Install

---

frontend/src/pages/Configure/Components.js
resources/scripts/mem.sh

* I've added `source /opt/parallelcluster/cfnconfig` which is redundant but allows people to use the script independent of the multi-runner script.
* The empty args needs to be tested.

Fix for memory.sh script

---

docs/content/02-tutorials/02-slurm-accounting.md

Link to slurm-accounting.sh was written as "slurm-accounting.py"
Fixed typo

Fixed typo in 02-slurm-accounting.md

---

frontend/src/pages/Clusters/Filesystems.js

If we are using a ParallelCluster version with a minor equal or greater than 2,
like 3.2.0b, support showing a link to FSx for OpenZFS and NetApp ONTAP file systems
in the cluster details' storage section.
In the case of ONTAP and OpenZFS we cannot mount an entire file system, so the id
links to the volume details, not to the file system details page. This is similar to
what happens with Ebs, while Efs and FSx for Lustre can mount the entire file system.
Tested with a cluster with ONTAP and OpenZFS shared storage, created with the following configuration:
``` yaml
HeadNode:
InstanceType: t2.micro
Ssh:
KeyName: ermann-dcv-dub
Networking:
SubnetId: <subnet id>
LocalStorage:
RootVolume:
VolumeType: gp3
Scheduling:
Scheduler: slurm
SlurmQueues:
- Name: queue0
ComputeResources:
- Name: …
```

Support FSx for OpenZFS and NetApp ONTAP in the cluster details' storage section

---

frontend/src/pages/Clusters/Filesystems.js

Refactor `StorageId` function by changing the conditional statement as indicated in [this comment](https://github.com/aws-samples/pcluster-manager/pull/164#discussion_r912972246).
Tested with internally and externally created shared storage.

Refactor StorageId function

---

api/PclusterApiHandler.py
frontend/src/model.js
frontend/src/pages/Configure/Storage.js

This PR adds support for [FSx ONTAP](https://aws.amazon.com/fsx/netapp-ontap/) and [FSx OpenZFS](https://aws.amazon.com/fsx/openzfs/).
- existing filesystem are filtered to apply only Lustre FS to the corresponding storage type, fixing a bug where Windows File Server FS were selectable
- return FSx volumes from the API
- add support for ONTAP/OpenZFS depending on the ParallelCluster version (3.2.0 and above)
- fixed a bug with EBS: linking an existing EBS volume wasn't working with the wizard
- created a new cluster with OpenZFS/ONTAP volumes attached
- verified that the new ZFS/ONTAP filesystem do not appear under the Lustre section
- verified that the Lustre storage is still working
- linked an existing EBS volume and verified that the wizard is working …

Add ONTAP/OpenZFS support

---

README.md
api/PclusterApiHandler.py
api/tests/test_pcluster_api_handler.py
frontend/src/auth/constants.ts
frontend/src/components/SideBar.js
frontend/src/model.js
frontend/src/pages/index.tsx
frontend/src/store.js
requirements.txt

In the context of implementing a configurable generic OIDC provider in current codebase, we want to get rid of the hardcoded dependencies of `cognito:groups` and introduce a configurable parameter for the name of the user groups claim in the JWT.
This PR aims to be a starting point in the direction of having a configurable OIDC provider in the ParallelCluster Manager. 
On the backend side, a new environment variable `USER_GROUPS_CLAIM` was introduced, with `cognito:groups` as default. On the frontend, the occurrences of `cognito:groups` were removed in favor of a generic `user_groups`, which is set in the `get_identity` function in the backend.
* Make the parameter effectively configurable through CloudFormation template. The overall UX setup will be handled in a dedicated story.
* Tested …

feat: make user roles claim in the jwt configurable, using 'cognito:groups' as default

---

api/PclusterApiHandler.py
api/tests/conftest.py
api/tests/test_pcluster_api_handler.py
infrastructure/pcluster-manager-cognito.yaml
infrastructure/pcluster-manager.yaml
pytest.ini

**Description of changes:**
This PR aims to parametrize the values needed for OIDC auth. Decoupling it from Cognito.
The goal is to have everything working as before, but being able to support another Auth provider _in the future_ more easily.
The defaults are meant to make the code work as it was before this change.
This PR depends on https://github.com/aws-samples/pcluster-manager/pull/172 and should be merged after that. (Done, rebased after that)
We decided to add `openid` as default in the `scopes`, as that should be the bare minimum to make the system work, in fact, without that, we would not be able to get the `idToken`.
The data that were taken by Cognito CLI before are taken by the `idToken` at the moment. We are putting all the data in the `idToken` in the `attributes` section …

OIDC parametrization

---

.log4brains.yml
decisions/20220708-use-log4brains-to-manage-the-adrs.md
decisions/20220708-use-michael-nygard-format-for-adr.md
decisions/README.md
decisions/index.md
decisions/template.md

This PR aims at introducing [ADRs](https://adr.github.io/) within the project. The goal is to document any architectural or meaningful decision we might make during the development, so that we can keep track of our decisions and the drivers that generated them.
In order to do that we decided to adopt [Log4brains](https://github.com/thomvaill/log4brains/tree/master#readme) as a tool for managing and writing our ADRs.
Please note that in order to use the tool for creating ADR you will need to install it globally, by doing:
```bash
npm install -g log4brains
```
Refer to the [Getting Started](https://github.com/thomvaill/log4brains/tree/master#-getting-started) section of the official Log4Brains repository for further information.
- Launched the preview with the `log4brains preview` command …

Adr adoption

---

frontend/src/model.tsx
scripts/run_flask.sh

Due to some CORS issues we found that Flask was listening on the same port used by Control Center on OSX ([thread here](https://developer.apple.com/forums/thread/682332)). The proposal is to switch to another port (5001) to fix this behavior.
Flask port changed to 5001 for development.
Spawned both frontend and backend and verified proper communication between the two.
[Apple forum thread](https://developer.apple.com/forums/thread/682332)

Change flask development port to fix ControlCenter issue

---

frontend/src/__tests__/storagCreationValidation.test.tsx
frontend/src/old-pages/Configure/Storage.tsx

This patch makes the wizard compliant with the limits for external
storage attachments.
When creating a new storage, we check that we are not violating the
constraint of the maximum number of storage of that given type we can
attach. The toggle that allows to switch between creation and attachment
of an existing storage is disabled according to the constraints of the
maximum number of storage that can be created or of existing storage that
can be attached.
- Unit tests.
- Manual tests:
- Attached Efs storage (creation).
- Attached 20 Efs storages (existing), verifying that the toggle is automatically set to "use existing" and disabled (greyed out).
- When the 20th existing Efs storage is attached, the toggle of the Efs storage to create is also disabled.
By submitting this pull request, I …

Make wizard compliant with limits for external storage attachments

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/HeadNode.tsx

When creating a new cluster, we allow the customer to use the
ConstrainRAMSpace option available in Slurm during the job
submission.
We want to meet features parity with PCluster 3.2.0 and it includes the support of memory based scheduling
* Added a toggle to enable memory based scheduling
* Deployed a new stack with PCluster 3.2.0b2 and tested
* Executed a DryRun with option enabled
* Executed a DryRun with option disabled (no new fields in the yaml)
* Executed a DryRun with option enabled and then disabled the toggle (no new fields in the yaml)

Add option, in the wizard, to enable memory based scheduling in Slurm

---

frontend/locales/en/strings.json
frontend/src/old-pages/Clusters/JobSubmitDialog.tsx

This patch allows the user to specify teh required memory when launching a job, if it is run on a Slurm cluster with memory based scheduling enabled.
- Tested with a cluster with memory based scheduling enabled, observed that the correct parameter `--mem <specified value>` was present in the request to `sbatch`.
- Tested with a cluster with memory based scheduling, without specifying the value, verified that it was not present in the `sbatch` parameters.
- Tested with a cluster without memory based scheduling, verified that the part of the dialogue that allows to specify the required memory for the job is not show.

Allow to specify reqired memory when launching a job

---

frontend/src/old-pages/Configure/HeadNode.tsx

Reverse tabnabbing is an attack that is possible when a link is
configured to open a new tab in a browser. If done incorrectly,
the new page is able to control the referrer and opener
objects of the parent window, and use that control to replace
the parent site with a phishing site.
The mitigation is add the noopener and noreferrer values in
the rel attribute in <a> tags.
Reverse tabnabbing is an attack that is possible when a link is
configured to open a new tab in a browser. If done incorrectly,
the new page is able to control the referrer and opener
objects of the parent window, and use that control to replace
the parent site with a phishing site.
The mitigation is add the noopener and noreferrer values in
the rel attribute in <a> tags.
Added the *noopener* tag
Locally tested. The new …

Fixing violation related to Defend Against Reverse Tabnabbing Attack

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Components.tsx
frontend/src/old-pages/Configure/MultiUser.tsx
frontend/src/old-pages/Configure/Queues.tsx

Add schedulable memory parameter in the queue section of the Wizard to reach feature parity with pcluster 3.2.0
(The flag to enable this param only with 3.2.0 will be added in a subsequent CR in addition to other related parameters)
1. Make configurable the HelpTextInput component
2. Add schedulable memory parameter
3. Add localization of strings for the interested part of code
Tested locally connecting to a PC version using 3.2.0b2, see video below
https://user-images.githubusercontent.com/83351137/179985446-761d5677-99c1-4814-98d9-978a3a3a1b84.mp4
This was dependent of the [PR related to the memory based scheduling](https://github.com/aws-samples/pcluster-manager/pull/193)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

Add schedulable memory parameter in the queue section of the Wizard

---

frontend/src/old-pages/Configure/HeadNode.tsx

Show enable memory based scheduling toggle only on PC >= 3.2.0
This is the approach currently used in the application, a new feature toggle mechanism will be enabled in the future
[fix(frontend) Show enable memory based scheduling toggle only if vers…](https://github.com/aws-samples/pcluster-manager/commit/d8b9ba63e4e45f6d10758dcec580842cabb5b70e)
Tested without defining API_VERSION env var (default is 3.1.0) and the toggle is not visible
Tested defining API_VERSION to 3.2.0 and toggle is visible and usable
Approach used in https://github.com/aws-samples/pcluster-manager/pull/164

Show enable memory based scheduling toggle only on PC >= 3.2.0

---

frontend/locales/en/strings.json

fix(frontend) Fix a wrong message in the Password Secret ARN field
The text was taken from https://docs.aws.amazon.com/parallelcluster/latest/ug/DirectoryService-v3.html#yaml-DirectoryService-PasswordSecretArn
fix(frontend) Fix a wrong message in the Password Secret ARN field
Locally, verifying new text appears

fix(frontend) Fix a wrong message in the Password Secret ARN field

---

api/PclusterApiHandler.py
api/tests/test_authenticate.py
api/tests/test_pcluster_api_handler.py
requirements.txt

This patch makes the API return:
- 400 if the login request does not contain a `code` (in the case of the OIDC provider redirecting the user after a successful login).
- 401 if the access token in the login or authenticate calls is missing.
- 401 if during authentication there is an issue with the signature.
- 403 if during authentication the group is not guest and is not among the groups in the decoded JWT.
- Unit tests
- Manual tests with Postman:
- Invoke a protected API without authentication, expecting 401.
- Through Postman, get a JWT through Cognito and invoke the same API attaching the JWT of the authentication, and get a 200.
- Modify a character in the JWT in the central part of the token to generate an invalid signature, expecting 401.
- Create a user on Cognito that is not …

Return 4xx in case of unauthenticated/unauthorized requests

---

frontend/src/old-pages/Clusters/Clusters.tsx

This change deselects the cluster after the delete process finishes.
Once the cluster is deleted by the backend it is no longer in the list. If that cluster is still selected, then we deslect it by removing the selection in the app state and the URL.
By creating a cluster, deleting it and leaving it selected and verifying that the page transitions to an unselected state.

`[Clusters]` Deselect a cluster after delete finishes

---

api/PclusterApiHandler.py
api/tests/test_get_app_config.py
app.py
frontend/package-lock.json
frontend/package.json
frontend/src/app-config/__tests__/index.test.ts
frontend/src/app-config/index.ts
frontend/src/app-config/types.ts
frontend/src/auth/__tests__/handleNotAuthorizedErrors.test.ts
frontend/src/auth/handleNotAuthorizedErrors.ts
frontend/src/model.tsx

This PR makes it so the frontend redirects unauthenticated or unauthorized users to the authorization server. As it is now, it basically replicates the behavior that [was previously on the backend](https://github.com/aws-samples/pcluster-manager/pull/216)
- Add `/get-app-config` route to share environment variables (and possibly other configs) to the client
- Add decorator over the `request` function to intercept 401/403 errors and redirect the user to the authorization server
- Manually, creation and deletion of a cluster
- Jest and Pytest

Redirect to authorization server upon 401/403 status codes

---

frontend/src/__tests__/storagCreationValidation.test.tsx
frontend/src/old-pages/Clusters/Clusters.tsx
frontend/src/old-pages/Configure/Components.tsx
frontend/src/old-pages/Configure/Storage.tsx
frontend/src/old-pages/Configure/Storage.types.ts

Restore the pipeline after the introduction of a linting stage with https://github.com/aws-samples/pcluster-manager/pull/221
- fix missing imports of `t`
- add proper types to the storage part
- 
- `npm test`
- `npx tsc -p tsconfig.json`
- manual tests inside the Storage part of the wizard

Fix types and missing imports

---

frontend/locales/en/strings.json
frontend/package-lock.json
frontend/package.json
frontend/src/model.tsx
frontend/src/old-pages/Clusters/Clusters.tsx
frontend/src/old-pages/Clusters/__tests__/Clusters.test.tsx
frontend/src/old-pages/Configure/Create.tsx

Rewrite Cluster list page incorporating a list of best-practices enhancements.
* Added i18n strings
* Leveraged userQuery in ListClusters() function
* Removed TS errors
* Added unit tests for `Clusters.tsx` 
`npm run dev` opened and navigated in cluster list page 
```
$ npm run test
Test Suites: 3 passed, 3 total
Tests:       18 passed, 18 total
Snapshots:   0 total
```

Cluster List enhancements 

---

frontend/src/model.tsx

This PR fixes an issue arising when non-admin accounts get to fetch the users' list. This may require a more structural fix in the long term, but we need a simple fix as right now non-admin users cannot access PCM
- only call `ListUsers` when the current user belongs to the admin group
- logged in as simple user and see that you can access the app

Fix ListUsers being called by non-admin accounts

---

.gitignore
frontend/src/auth/__tests__/handleNotAuthorizedErrors.test.ts
frontend/src/auth/handleNotAuthorizedErrors.ts

This PR introduces the use of the state parameter on the frontend, populated with a random string.
This is part of the [RFC for OAuth2](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1)
State parameter is currently [supported by Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/login-endpoint.html).
Right now we don't actually make use of the state parameter but introducing it allows us to better support other OIDC providers like Okta that request it as mandatory (even if the RFC puts it as recommended).
- added `/frontend/tsconfig.tsbuildinfo` to .gitignore since it's used to check issues with typescript before doing the PR
- added a function to generate a simple random string to set the `state` parameter
- adjusted a test to reflect this change
This has been …

Use "state" parameter for OAuth2 initiated login

---

frontend/src/old-pages/Clusters/Clusters.tsx

Currently in PCM we have a TypeScript error due to the fact that the header property of the `SplitPanel` component takes a string while we are passing a `<Header>` component instead.
This is not compliant with Polaris design system, thus we should move actions buttons from `SplitPanel` header to `Table` header.
* Moved `Actions` component from `SplitPanel` to `Table` header
* Manually tested all action buttons with success
* Cluster stopped / started
* Shell
* Filesystem
* Edited / deleted

refactor: move Actions buttons from split panel header to table header

---

frontend/locales/en/strings.json
frontend/src/old-pages/Clusters/Actions.tsx
frontend/src/old-pages/Clusters/Clusters.tsx

Currently actions buttons in Clusters page use a mix of Polaris and MUI icons, which result in a not uniform sizing:
This PR aims at solving this issue by applying MUI icons to all actions buttons.
Changes applied:
* Verified manually that each button behaves as expected
* `npm run test` successful 

fix: use MUI icons in all actions buttons to fix incorrect sizing

---

frontend/locales/en/strings.json
frontend/src/components/ValidationErrors.tsx

Remove the use of MUI in the ValidationErrors component.
Looking at the 3 options for success, warning and error for a cluster config:

`[components/ValidationErrors]` Remove MUI.

---

infrastructure/pcluster-manager.yaml

Currently `pcluster-manager` stack cannot be updated in case of a bumped version due to insufficient policies in EcrImageDeletionLambdaRole.
* Added missing policies for **EcrImageDeletionLambdaRole** in `pcluster-manager.yaml` file
* Manual tests
* Created the stack (3.1.3) and attempted to upgrade to 3.1.3 --> Stack Update Failed EcrImageRemover Error in CloudFormation
* Created the stack (3.1.3) with an API template with the changes in this commit
Attempted to upgrade to 3.1.4 --> Stack updated Succeeded
* https://github.com/aws/aws-parallelcluster/pull/4194
* https://github.com/aws/aws-parallelcluster/pull/4206

fix: add missing policies for EcrImageDeletionLambdaRole

---

frontend/src/__tests__/util.test.tsx
frontend/src/old-pages/Configure/Storage.tsx
frontend/src/util.ts

This PR removes the MUI slider so that we have one less dependency on a second UX framework.
- Add a util clamp function
- Remove the MUI Slider, replace with an input that clamps value on blur
- Convert EFS throughput input to use same clamping function
- Add types to options and remove ts-expect-errors
Manually tested the Lustre Storage Capacity input with: letters, negative numbers, positive numbers, numbers out of step
Manually tested the EFS Throughput  input with: letters, negative numbers, positive numbers, numbers out of step

`[Storage]` Remove MUI Slider, various chores.

---

requirements.txt

This PR locks dependencies to the specific version we are currently using.
**Please note:**
The requirements.txt file is currently missing `flask` (and may be missing something else). Also we currently list `pyyaml` which I don't think is used anywhere. We should address this issues
- change `requirements.txt` via `pip freeze`
- running `pip install -r requirements.txt` yields `Requirement already satisfied` for every dependency listed in the requirements file
- cleaned up the virtualenv using `pip uninstall -y -r <(pip freeze -r requirements.txt)` and reinstalled dependencies via `pip install -r requirements.txt`. Installed versions match the content of the frozen requirements.txt
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Freeze requirements.txt

---

.gitignore
infrastructure/pcluster-manager.yaml

Bump version of PC and PCM to `3.2.0`.
- Deployed new PCM stack in personal account.
- Tested creation of a cluster.
- Updated to image to latest version (`update.sh --local`).
- Tested creation of a cluster.

Bump version of PC and PCM to 3.2.0

---

api/PclusterApiHandler.py

Fixed a small bug on missing id_token in requests
It caused a 500 in the get_identity_() controller function
This has been tested in a deployed environment.

fix: on missing idtoken or accesstoken return 401

---

api/PclusterApiHandler.py
api/tests/test_logout.py

This PR fixes the logout button resulting into a 400 for the user
**Please note**: This PR does not introduce actual logout to the auth provider (Cognito). It simply fixes the user facing issue of having a broken experience when logging out
- redirect to `/index.html` upon logout
- add tests to `logout()` function
Fix logout button sending users to a broken URL
- Manually, logged out and checked redirection worked out fine
- pytest

Fix logout running into a 400

---

frontend/src/components/TopBar.tsx
frontend/src/old-pages/Clusters/Clusters.tsx
frontend/src/old-pages/Clusters/__tests__/Clusters.test.tsx

This PR resolves an issue emerged from https://github.com/aws-samples/pcluster-manager/pull/219 where a user might not get a clusters list update when a region is changed. This happens because when you switch the region, `react-query` is not informed that the change happened, and the user still sees the old data.
- invalidate all queries state when a region is changed
- refactored part of the clusters list to poll the list status by leveraging react-query
- removed a side effect from the clusters list update function that might cause unwanted navigation on a cluster update
- created a new cluster and verified that is selected
- deleted the cluster and verified that becomes unselected
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Fix react query updates

---

frontend/package-lock.json
frontend/package.json
frontend/src/auth/handleNotAuthorizedErrors.ts
frontend/src/model.tsx
frontend/src/util.ts

This PR removes a dependency we don't need at the moment. This is also an easy solution to our [CI failing like this](https://github.com/aws-samples/pcluster-manager/runs/7670526834?check_suite_focus=true)
- remove `uuid`
- refactor `oauth2StateParameter` to be a generic util
- manually tested notifications
- jest

Remove uuid and adopt simple util to generate a random string

---

frontend/src/old-pages/Clusters/Details.tsx
frontend/src/old-pages/Clusters/__tests__/util.test.tsx
frontend/src/old-pages/Clusters/util.tsx

Details.tsx has some code that checks whether Slurm Accounting is active on a cluster. I moved this to utils so that it can be reused to check for other custom bootstrap actions (specifically Slurm REST API).
- Checked that the accounting tab was visible only when an accounting cluster was selected.
- Created tests for `getScripts()`

Move code for getting list of custom bootstrap actions to util.tsx

---

frontend/locales/en/strings.json
frontend/src/i18n-resources.d.ts
frontend/src/old-pages/Configure/Components.tsx

This PR uses Typescript to check if a key supplied to the translation function exists, and if it does not exist, trigger an error during the build.
- all keys of `string.json` are now suggested when using the translation function
- fix an existing key which didn't exist
- run `npm run ts-validate` and verified that the project builds correctly

Type translations

---

infrastructure/pcluster-manager.yaml

This patch removes the unused `EcrImageBuilderSNSTopic` from the PCM CloudFormation template. The topic was initially added to the PC API CloudFromation template in [#3054](https://github.com/aws/aws-parallelcluster/pull/3054) and was used when updating the Docker image to switch the image, backing the PC API Lambda function. This SNS topic is not used in the PCM template and can therefore be removed.
Deployed a new PCM Cfn stack and performed the relevant tests in the checklist below.

Remove superfluous SNS topic from PCM Cfn template

---

api/PclusterApiHandler.py
api/tests/test_get_identity.py
api/tests/test_pcluster_api_handler.py

Currently PCM retrieves `user_groups` and `username` claims from the access token, and store all the claims of the id token in the `attributes` field of the object returned by the `get_identity` function.
In order to avoid forcing the customer to specify which attributes will end up in the access token and which ones in the ID token, we have to refactor our current logic.
The idea is to get user attributes from the access token first and then from the id token, resolving all conflicts in favor of the id token.
* `user_groups`, `username` and `email` claims are now retrieved from both access token and id token, giving higher priority to the latter (i.e. if a claim is available in both tokens, the id token claim will be returned in the identity object)
* dropped unused parameters in the …

Handle id token and access token attributes in get_identity

---

api/PclusterApiHandler.py
app.py
frontend/locales/en/strings.json
frontend/src/model.tsx
frontend/src/old-pages/Clusters/Cost.tsx
frontend/src/old-pages/Clusters/Details.tsx

This adds a tab called "Cost" which summarizes Cluster cost by pulling in data from cost-explorer and graphing it by instance type. Also, this includes a button to activate cost allocation tags, which is a necessary pre-requisite for cost explorer.
- Included new Cost.tsx file
- Added route `/manager/graph_data?cluster_name=Cluster&Start=Start&End=End/`
- Added route `/manager/activate_tags/`
- Added route `/manager/check_tag_status/`
- Tested locally using created clusters
https://user-images.githubusercontent.com/68314782/180088672-fad78396-854a-425f-92c8-7c8152289d64.mov

Cost Explorer

---

infrastructure/pcluster-manager-cognito.yaml

Changing email as a mutable field to avoid breaking second login in Cognito setup with AD SAML federation.
- Email field `mutable` attribute to `true` from `false`
- Fix: Email field `mutable` attribute set to `true` to fix an issue where second login would break authentication process in Cognito

Mutable email field in pcluster-manager-cognito CloudFormation template

---

.github/workflows/pull_request.yml

Running the unit tests is not needed when pushing to `main`: a direct push to `main` is disabled and thus tests are not needed.
Anyway, tests are done for safety before deploying the updated code in the `demo` environment, see #257.

Remove push to main from PR workflow triggers

---

.github/pull_request_template.md
PROJECT_GUIDELINES.md
README.md

This PR adds a Contributing section to our README, with Project Guidelines to be respected to maintain high quality code
- add PROJECT_GUIDELINES.md
- add Contributing section to README.md
- link to Contributing Guidelines and Project Guidelines from our PR template
- browsed [the branch](https://github.com/aws-samples/pcluster-manager/tree/project-guidelines) to check that links work

Add PROJECT_GUIDELINES to Contributing section

---

infrastructure/environments/demo-cfn.yaml
infrastructure/environments/demo-variables.sh
infrastructure/github-env-setup.yml
infrastructure/pcluster-manager.yaml
infrastructure/readme.md
infrastructure/update-environment-infra.sh

Provides an easy way to update the infrastructure of a specific environment on which PCM is running.
The script is run locally because of the complex IAM policy required by the workflow (it may be added later).
See the infrastructure readme or the script itself for more info.
- add a new parameter to specify the infrastructure bucket on CFN
- if left empy it will use the public yaml files
- if a user provides a custom bucket it will use the files inside it
- add a script to update a CFN stack
Launched `./infrastructure/update-environment-infra.sh demo` on the demo environment and verified the stack is updated correctly
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the …

Script to update a CFN stack

---

api/PclusterApiHandler.py
api/tests/test_submit_job_script.py
app.py
frontend/locales/en/strings.json
frontend/src/model.tsx
frontend/src/old-pages/Clusters/JobSubmitDialog.tsx
frontend/src/old-pages/Clusters/Scheduling.tsx

Added an option to submit jobs by file upload or manual entry through a code editor. This is a proof of concept for my Slurm REST API script. Jobs entered through this method are submitted through the Slurm API rather than SSM.
- Added a new component JobField to simplify JobSubmitDialog.
- Added a new API endpoint to proxy requests to the Slurm REST API.
- Added new `script` submit option, which is only selectable when a cluster has the Slurm REST API Custom Bootstrap Action enabled. ~~(waiting on #227)~~
- Fixed a couple bugs/issues along the way
- State did not clear when user inputted and then deleted a job property, which caused the job to fail
- Error messages were never cleared
- Refactored SubmitJob endpoint to return a Promise
- Use translations in JobSubmitDialog.tsx
Manually …

Add manual script entry as a new job submission option

---

scripts/README.md
scripts/rollback_awslambda_image.sh
scripts/rollforward_awslambda_image.sh

Add scripts to rollback and rollforward the latest aws lambda image.
The scripts could have been merged into just one, but I thought it would been easier for an operator launch to different scripts instead of messing with arguments of a single script.
There are no README instruction for the script at the moment, the usage will be explained in the rollback runbook we will have soon.
Just added two scripts.
N/A
Tested in a personal private ECR repo, see video below
https://user-images.githubusercontent.com/83351137/186454157-cf36f401-dbd1-468b-a128-2a1f3a5f446d.mp4
N/A
-Not relevant …

release - Add scripts to rollback and rollforward the latest aws lambda image

---

infrastructure/github-env-setup.yml

For our security standards, every S3 bucket must have encryption enabled. This PR introduces encryption to the already created S3 bucket, the one holding the infrastructure files.
- add default encryption (S3 keys) to the S3 bucket holding the infrastructure files
Updated the CFN stack and verified the default encryption.
- N/A

Add encryption to S3 bucket for infrastructure

---

docs/content/02-tutorials/02-slurm-accounting.md
docs/content/02-tutorials/05-cloud9.md
docs/content/02-tutorials/06-downloading.md
frontend/src/components/FileChooser.tsx
frontend/src/old-pages/Configure/Source.tsx
frontend/src/old-pages/CustomImages/ImageBuildDialog.tsx

- Removed a duplicate component
- During cluster configuration, using a cluster that is undergoing deletion as a template leads to creation failure. I removed the possibility of selecting these clusters.
- Fixed typos in tutorials
Manually - deleted a cluster and checked to make sure that it didn't show up in cluster configuration

Miscellaneous chores

---

infrastructure/pcluster-manager.yaml

Set Cognito nested stack deletion policy to Retain to avoid cancellation of the nested stack when the main stack is deleted
CI(templates) - Set Cognito deletion policy to retain
- Cognito nested stack has now deletion policy set to Retain
Created a new PCM test, deleted main stack, Cognito stack deletion was skipped
N/A
Not relevant

CI(templates) - Set Cognito deletion policy to Retain

---

CONTRIBUTING.md
frontend/git-secrets-conf.sh
frontend/package.json

This PR introduces an automation for the setup of git-secrets forcing the installation of the relevant git hooks during the npm "prepare" phase, this works only if git-secrets is installed, so I added installation instructions in the CONTRIBUTING.md file
We may need to add more patterns in the future, but this can be done iteratively
*    security - Force the installation of git hooks related to git-secrets at npm "prepare" phase
*    documentation (contributing) Adding instructions to install git-secrets
*    refactor - Adding shebang to bash script
*    refactor (ci) - Execute the git-secrets installation only if we are not on CI
N/A
- Run `npm install` without git-secrets installed -> fails
- Run `npm install` with git-secrets installed -> succeeds
- Hooks installed
- Tried to commit a …

Add git-secrets automation

---

infrastructure/pcluster-manager.yaml

ONTAP/ZFS volumes are not visible inside the wizard because the corresponding IAM permission has not been added.
Fixes #276.
- add the `fsx:DescribeVolumes` to the Lambda role
Fix display of ONTAP/ZFS volumes in the wizard
- edited the template of a test stack with the new permission and verified that the Ontap volume is shown

Add missing permissions to describe FSx volumes

---

frontend/.eslintrc.json
frontend/.husky/commit-msg
frontend/.husky/pre-commit
frontend/.husky/prepare-commit-msg
frontend/.prettierrc.json
frontend/git-secrets-conf.sh
frontend/package-lock.json
frontend/package.json
frontend/scripts/git-secrets-command.sh

Currently no tooling is available in the project to ensure that all changes follows the same formatting rules and avoids the use of some bad patterns. This PR aims to include in the project standard tools like ESLint (already bundled by Next), Prettier and lint-staged. 
Furthermore, it introduces [husky](https://github.com/typicode/husky) to the project for handling git hooks in a simplified and more organized manner.
Prettier rules have been chosen following JS/TS best practices.
* ci - added linting (`eslint`) and formatting (`prettier`) to the project
* ci - leverage `lint-staged` to enhance performance applying linting to staged files only
* refactor - use husky for managing git hooks, including `git-secrets`
N/A
* Run `npx eslint --fix` on a subset of files, verified that files are …

Add linting and formatting

---

.github/workflows/demo_deploy.yml

After #291 , the deploy demo action needs to be adjusted since it doesn't pass the additional parameter `--stack-name` now required.
- correct usage of update.sh
#291 

Fix update.sh script usage after PR 291

---

frontend/package.json
infrastructure/github-env-setup.yml
scripts/update.sh

In the previous PR #291 there was an hardcoded string used, instead of the correct parameter introduced in that PR, plus the GH action presents a new error `bash not found` that we're trying to solve.
- github-env-setup.yml has been edited to introduce the newly necessary policy the the role used, in order to perform the DescribeStackResources action
- the package.json `prepare` script now uses `/bin/bash` instead of `bash` only to perform its operations
- the update.sh script correctly uses the `--stack-name` parameter and the `region` value to perform its operation against AWS APIs.
This was tested both locally and on GitHub actions deploying the code and temporarily changing the GH actions to perform scripts only on the wip branch. 
#291 
#292 
By submitting this pull request, I …

Fix CloudFormation invocation in update.sh script + "bash not found" error

---

api/tests/test_build_flask_app.py
api/utils.py
app.py

This PR makes it so CORS is enabled only in `dev` environment. We don't need it in production
- enable CORS only when `running_local()` is `True`
- Disable CORS headers in production
- unit tests
- ran locally in both scenarios and looked at the network panel to see whether the headers were being added or not

Only enable CORS in development

---

frontend/locales/en/strings.json
frontend/src/__tests__/DescribeCluster.test.ts
frontend/src/model.tsx
frontend/src/old-pages/Clusters/Clusters.tsx
frontend/src/old-pages/Clusters/__tests__/util.test.ts
frontend/src/old-pages/Clusters/util.tsx

Fixes #271 
This PR introduces a check to make sure we don't fetch cluster details when the cluster is in an unstable states. ~~States are listed and can be easily changed in the future~~
Whenever the describe cluster fails, the app shows an error message and stops fetching other data (preventing misleading errors from happening)
If we want to prevent the first error message from showing, we should move the error handling outside of the `DescribeCluster` command and handle it on a case-by-case basis (I'd do this in another PR anyway)
- avoid describing the cluster if it is is an unstable state
- fix error message showing `&nbsp;` symbols
Fix cluster selection not working when cluster is in CREATE_FAILED state
- unit tests
- locally, mocking the state of the cluster
- mocked a …

Cluster in CREATE_FAILED state cannot be selected/deleted

---

infrastructure/pcluster-manager.yaml

This patch makes creation of Cognito resources in our `pcluster-manager.yaml` Cfn template conditional on selecting *Cognito* as the OICD provider (it is the default option).
_**Update**: removed Okta as an option as we still don't support it, we will reintroduce it once we have a working implementation._
- Deployed a PCM stack with *Cognito* as OICD provider, verified it by running the relevant PR quality checklist tests.
- Deployed a PCM stack with *Okta* as OICD provider, verified that Cognito resources were not created (this includes environment variables in the PCM Lambda, etc.). …

Create Cognito resources only when it is chosen as OICD provider

---

infrastructure/github-env-setup.yml
infrastructure/readme.md

This PR adds a new `PrivateInfrastructureUpdateRole` IAM role to the `github-env-setup.yml` template that is to be assumed when running the `update-environment-infra.sh`
Another PR will follow with the workflow running the script and assuming this role
- add `PrivateInfrastructureUpdateRole` to the `github-env-setup.yml`
- add role to the CFN template that is to be assumed when updating the infrastructure via CI
- created the Role and Policy and ran the update script manually
- tested the created Policy with https://policysim.aws.amazon.com/home/index.jsp and made sure only intended actions are allowed …

Add role to update infrastructure via GitHub actions

---

infrastructure/pcluster-manager.yaml

* Refactored `PclusterManagerExtraPolicies` separating it in three different policies clarifying the scope
* Removed wildcards in policies where possible
* Deployed stacks on my personal account
* Performed tasks in PR Quality Checklist successfully
* Created cluster with EFS
* Created cluster with FSx
* Submitted a job through SSM
* https://quip-amazon.com/9MgvA9mYGAzt/PCM-IAM-Resources

Refactor PclusterManagerUserRole policies

---

.github/pull_request_template.md

In case the infrastructure CloudFormation templates get edited, it's important to make sure the update infra script from the GH Action still works. This usually involves changes in the role used by the GH Action to perform certain actions. If new actions are needed, new policies need to get added to the role used by the GH Action itself.

Added checkbox for infrastructure edits check

---

scripts/update.sh

[The last run of Actions](https://github.com/aws-samples/pcluster-manager/actions/runs/3182434830) was failing after fixing the script invocation (using the `-e` flag).
The command failing the build is the one to retrieve the region: this is not really needed as it's better to specify the region manually, thus has been removed.
Run the `update.sh` script locally and verified the region is taken correctly.

Force region to be specified in update.sh

---

infrastructure/pcluster-manager.yaml

Removed unnecessary OIDC provider option from the input parameters and the related `UsesCognito` condition from the CloudFormation template.
- `infrastructure/pcluster-manager.yaml`
This has been tested by deploying a new stack and making sure
- the provider option doesn't appear
- the stack gets deployed correctly
- the login works

Removed OIDC provider option and related "UsesCognito" condition

---

infrastructure/pcluster-manager.yaml

We use IMDSv2 to copy the pubilc Docker image into the customer's private ECR repository. This patch makes usage of IMDSv2 required in ImageBuilder's build instance (i.e. it disabled IMDSv1). This is okay since we don't allow the customer to specify custom components where they could make `curl` calls to IMDSv1, etc. (see the `EcrImageRecipe`).
Stack deployed in personal account.

Enforce IMDSv2 for ImageBuilder instances

---

frontend/locales/en/strings.json
frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
frontend/src/feature-flags/featureFlagsProvider.ts
frontend/src/feature-flags/types.ts
frontend/src/old-pages/Configure/HeadNode.tsx
frontend/src/old-pages/Configure/SlurmSettings.tsx
frontend/src/old-pages/Configure/__tests__/slurmAccountingValidation.test.ts

Currently in pcluster-manager users can leverage Slurm Accouting feature by following [this procedure](https://pcluster.cloud/02-tutorials/02-slurm-accounting.html), which is based on the Multi-Runner script feature.
From ParallelCluster 3.3.0, users are able to provide their own database that Slurm will use to store accounting data. ParallelCluster will take care of configuring the scheduler db daemon and its communication with the database server.
This PR aims at providing a new `Slurm Settings` section in the `HeadNode` wizard configuration section to specify the following paramters:
* `Database`: the uri of the database
* `Username`: username of the admin user of the database
* `Password`: Secrets Manager arn of the plain text password of the database admin
* Added Slurm Accounting …

Add Slurm Accounting configuration in wizard

---

infrastructure/github-env-setup.yml

Added to policies to the PrivateInfrastructureUpdateRole to allow the release infrastructure script to work.
This has been tested updating the current github-env stack in ClouFormation with the one in this PR.

Fix release infra: Added necessary policy to 'PrivateInfrastructureUpdateRole'

---

frontend/src/old-pages/Clusters/Details.tsx
frontend/src/old-pages/Configure/SlurmSettings.tsx

Following Slurm Accounting integration in: https://github.com/aws-samples/pcluster-manager/pull/320, this PR aims to fix two issues:
1. Slurm Accounting tab did not show up in case Slurm Accounting was enabled through Slurm Settings section
2. If Slurm Accounting fields were filled and then deleted, the validation process did not take care of clearing the state of the fields, resulting in a YAML configuration file with empty parameters
* Created a cluster with `slurm_accounting` feature flag disabled
* Verified that if accounting fields are filled and then deleted, the resulting YAML configuration does not have `Database` section included
* Created a cluster with `slurm_accounting` feature enabled
* Submitted successfully 3 sample jobs
* Retrieved accounting info through `sacct` command …

Fix Slurm Accounting visualization and validation

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/HeadNode.tsx
frontend/src/old-pages/Configure/SlurmSettings/ScaledownIdleTimeForm.tsx
frontend/src/old-pages/Configure/SlurmSettings/SlurmAccountingForm.tsx
frontend/src/old-pages/Configure/SlurmSettings/SlurmSettings.tsx
frontend/src/old-pages/Configure/SlurmSettings/__tests__/ScaledownIdleTimeForm.test.tsx
frontend/src/old-pages/Configure/SlurmSettings/__tests__/slurmAccountingValidation.test.ts

This PR adds support for the `ScaledownIdletime` Slurm setting
- refactor `SlurmAccountingForm` into its own component
- add `ScaledownIdleTimeForm` component
Add support for the the [`ScaledownIdletime` Slurm setting](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmSettings-ScaledownIdletime)
- unit tests
- manually tested both setting and unsetting the property
- manually tested the error case
- [ScaledownIdletime documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmSettings-ScaledownIdletime) …

Add Slurm ScaledownIdleTime support

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/HeadNode.tsx
frontend/src/old-pages/Configure/Queues.tsx
frontend/src/old-pages/Configure/SlurmMemorySettings.tsx

Following the UX refactoring of ParallelCluster Manager, this PR aims at moving the 'Enable Slurm Memory Based Scheduling' toggle from the HeadNode to the Queues wizard section, in a new, dedicated box.
With PC 3.3, multiple `InstanceTypes` per queues have been introduced. We need to disable `Slurm Memory Based Scheduling` in case of multiple instance types have been selected. This issue will be handled in a dedicated PR.
* Moved Slurm memory based scheduling from 'HeadNode' to 'Queues' wizard section
* Successfully created cluster with Slurm Memory Based Scheduling enabled
* Successfully created cluster without Slurm Memory Based Scheduling enabled
* Info button works as expected
In order to increase the likelihood of your contribution being accepted, please make sure you have read both …

Move Slurm memory based scheduling from 'HeadNode' to 'Queues' wizard section

---

infrastructure/environments/demo-cfn.yaml
infrastructure/pcluster-manager.yaml

Update the demo environment to the latest version available of ParallelCluster. 
This PR simply aligns the template with what's on the demo environment since it has been already updated manually.
Update the relevant infrastructure files for PC 3.3
Updated the stack manually through CFN and verified the portal is running with the latest version

Update PC version to 3.3.0b1

---

infrastructure/pcluster-manager.yaml

Reverting the bump of PCM version in the infrastructure files.
This is not needed at the moment - it will be done when doing a new release - and it breaks the demo environment deploy due to lack of permissions when re-creating CFN resources.
Manually updated the template with the change.

Revert PCM version in infra

---

frontend/locales/en/strings.json
frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
frontend/src/feature-flags/featureFlagsProvider.ts
frontend/src/feature-flags/types.ts
frontend/src/old-pages/Configure/SlurmSettings/QueueUpdateStrategyForm.tsx
frontend/src/old-pages/Configure/SlurmSettings/SlurmSettings.tsx
frontend/src/old-pages/Configure/SlurmSettings/__tests__/QueueUpdateStrategyForm.test.tsx

This PR adds support for the `QueueUpdateStrategy` Slurm setting
- add `slurm_queue_update_strategy` feature flag and map it to PC version 3.2.0
- add `QueueUpdateStrategyForm` component
- hide component when flag is not active
Add support for the the [QueueUpdateStrategy Slurm setting](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmSettings-QueueUpdateStrategy)
- unit tests
- manually tested successful dry run for each of the three options
- [QueueUpdateStrategy documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmSettings-QueueUpdateStrategy)
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing …

Add Slurm QueueUpdateStrategy support

---

.github/workflows/demo_deploy.yml

Deploy to the demo environment can fail if PRs are merged over a short period of time.
See this [run](https://github.com/aws-samples/pcluster-manager/actions/runs/3310735081/attempts/1) for a failed CFN update, because another one was already in progress.
Limits the deploy to demo to have only 1 job running at a time (concurrency=1)

Limit demo deploy concurrency

---

Dockerfile.awslambda
awslambda/entrypoint.py

This PR originates after new errors rising from the demo environment:
`[ERROR] Runtime.ImportModuleError: Unable to import module 'awslambda.entrypoint': No module named 'aws_xray_sdk' Traceback (most recent call last):`
Specifically, AWS Lambda Powertools [released a new breaking version](https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v2.0.0), causing the bad behaviour.
We are impacted because the Powertools are outside the requirements.txt and don't have a fixed version.
Fixed the version of AWS Lambda Powertools
Run a Docker build of the Lambda image and verified it's working correctly …

Fix Lambda powertools version

---

.github/workflows/gh-pages.yml
decisions/20221025-public-documentation-release.md

Changes the trigger of public documentation workflow to deploy updates only when a release is made. This is to avoid inadvertent deployments of documentation regarding unreleased PCM or PC versions.

Deploy documentation only on releases

---

frontend/next.config.js

This PR removes unnecessary code from NextJS config file.
Following #336 the experimental flag to disable `next/image` for static exports is not relevant anymore
- remove unnecessary experimental flag from `next.config.js`
- by running `npm run export` and checking that there are no errors

Remove useless experimental flag from NextJS config

---

frontend/src/components/SideBar.tsx

This PR fixes the following scenario:
- full page reload of the `/` page
- sidebar active item not being highlighted
- derive `activeHref` from the pathname at every location change
- full page reload
- navigation through all sections
- full page reload of deep nested path (`/clusters/{clustername}`)

Fix sidebar activeHref not being set on full page reload

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Queues/SlurmMemorySettings.tsx
frontend/src/old-pages/Configure/Queues/__tests__/hasMultipleInstanceTypes.test.tsx
frontend/src/old-pages/Configure/Queues/queues.types.ts

With ParallelCluster 3.3.0, multiple instance types per compute resource can be selected. 
If a user selects more than one instance type (in at least one compute resource, and in any queue) we need to ensure that Slurm Memory Based Scheduling cannot be enabled.
* Disable Slurm Memory Based Scheduling toggle if multiple instance types are selected
* Unit tests
* Verified with 3.3.0 that if multiple instance types are selected, slurm memory based scheduling toggle is disabled and an alert is shown
* Verified with 3.2.0 that alert is never displayed and slurm memory based scheduling can be checked/unchecked …

Disable Slurm Memory Based Scheduling toggle if multiple instance types are selected

---

frontend/src/__tests__/CreateCluster.test.ts
frontend/src/model.tsx
frontend/src/old-pages/Configure/Create.tsx

This PR fixes the Disable Rollback feature not actually disabling the stack rollback on failure
- add spec for the `CreateCluster` command
- use correct `rollbackOnFailure` query parameter as [documented](https://github.com/aws/aws-parallelcluster/blob/develop/api/spec/openapi/ParallelCluster.openapi.yaml#L115)
Fix Disable Rollback toggle not actually disabling the stack rollback on failure
- unit tests
- creating a cluster and checking with `aws cloudformation describe-stacks --stack-name myteststack` that `DisableRollback` is set to `True`
- [Stack failure options](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stack-failure-options.html)
- [PC API documentation](https://github.com/aws/aws-parallelcluster/blob/develop/api/spec/openapi/ParallelCluster.openapi.yaml#L115) …

Fix "Disable Rollback button not working"

---

requirements.txt

This PR pins Flask version to 2.1.2, instead of letting the dependent packages (such as Flask-REST) to install the most current version of Flask
- add `Flask` 2.1.2 to `requirements.txt`
- Starting from an environment with Flask 2.2.2: 
- removed every Python dependency, and reinstalled
- checked with [`pipdeptree`](https://pypi.org/project/pipdeptree/) the actual installed version is 2.1.2
Command output
```
Flask-Cors==3.0.10
- Flask [required: >=0.9, installed: 2.1.2]
....
Flask-RESTful==0.3.9
...
- Flask [required: >=0.8, installed: 2.1.2]
....
```
By submitting this pull …

Pin Flask version in requirements.txt

---

frontend/src/old-pages/Clusters/Actions.tsx

ParallelCluster does not allow updating a cluster when the version of PC used to create such cluster does not match the version of PC in use. 
On ParallelCluster Manager side, allowing to do so, has the following consequences:
* the editing user flow will potentially break client-side
* the PC backend will return an error anyway, when submitting the update at the end of the wizard
* Disabled cluster edit button in case ParallelCluster API full version does not match cluster full version
* Locally exported `API_VERSION` env variable to `3.3.0`
* Verified that, when selected, clusters with version `3.3.0` have *Edit* button enabled
* Verified that, when selected, clusters with version different from `3.3.0` have *Edit* button disabled
In order to increase the likelihood of your contribution …

Disable cluster edit button in case ParallelCluster API full version does not match cluster full version

---

decisions/20221107-adopt-github-labels-to-allow-automating-release-changelog-creation.md

Add ADR for the use of Github automatic changelog creation tool through labels.

ADR: automating release changelog creation

---

.github/release.yml

Add `release.yml` to the `.github` folder to allow the [automatic generation](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) of the release changelog when performing a new release from the GitHub UI.
This config only considers two sections, using the `release-include` label for the "Features" section and a "Other Changes" section for all the other labels, excluding the following:
- DON'T MERGE
- duplicate
- invalid
- question
- wontfix
This first minimal version should be tested during our next release.
- [GitHub doc](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)
In order to increase the likelihood of your contribution being accepted, please make sure you have read …

Add GitHub release config for changelog automation

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Source.tsx

Currently it is possible to choose as a template a previously created cluster from the wizard to use for a new cluster the user wants to create.
ParallelCluster doesn't allow cluster creation with configuration versions different from the PC version in use. So using a configuration from a previously created cluster (with a cluster config version from a different PC version) would raise an error on the PC side.
This PR aims to solve this issue, by filtering out clusters in the 'From Cluster' dropdown in case they do not match the exact version of PC.
* Exported locally `API_VERSION` env variable
* Verified that clusters with the same version are displayed in the dropdown
* Verified that clusters with a different version are not displayed in the dropdown
In order to increase the likelihood …

Filter out clusters in configuration source 'From Cluster' dropdown in case they do not match up to the minor version of PC

---

frontend/src/old-pages/Configure/Source.tsx

After the latest changes there's a bug preventing the user from filling the wizard if a cluster is currently being deleted.
Filter out all clusters in deletion from the cluster import options
- Start a wizard when a cluster is not being deleted, everything works correctly
- Start a wizard when a cluster is being delete: the product is not crashing and the cluster is not listed in the select

Fix a bug crashing the wizard when there's a cluster in deletion

---

infrastructure/github-env-setup-prod.yml

When releasing ParallelCluster Manager to customers a new tag is created.
Previously, to authenticate with AWS there was a strong check with the source branch: in the release case there's no branch and this was failing.
- authenticate the release role only if coming from a tag
https://github.com/aws-samples/pcluster-manager/actions/runs/3427737937

Match tags when authenticating to AWS in a release

---

frontend/src/old-pages/Clusters/Logs.tsx
frontend/src/old-pages/Clusters/StackEvents.tsx

Cluster logs are not searchable anymore following the release of 3.3.0 (see #356).
The problem started after linting the codebase, which changed the dependencies of the search hook of the component. 
Fixes #356.
- removed the problematic dependency from search hook
Manually searched logs in the Logs and Stack Events tabs

Fix Logs and Stack Events not being searchable

---

infrastructure/environments/demo-cfn.yaml
infrastructure/update-environment-infra.sh

This PR solves an issue where our demo env would file updating the infrastructure because of the new tagging strategy in our docker images.
- added `PublicEcrImageUri` to point to the latest image available in the repo
- fixed a typo in `update-infrastructure-infra.sh` in comments
Manually

Update CF parameters used in demo infra + fix typo

---

api/exception/__init__.py
api/exception/handlers.py
api/tests/test_exception_handlers.py
api/tests/test_push_log.py
app.py

Added a public endpoint to allow the frontend to push log entries to the backend.
- Added a new exception handler to handle ValueError in case of API validation error
- Added a `/push-log` endpoint to log the log entries from the frontend
- Added tests for newly added ValueError exception handler and far all validation cases of the new endpoint
Unit tests and manual integration tests

Added public endpoint to push log entry to from the frontend

---

api/PclusterApiHandler.py
api/tests/test_exception_handlers.py
app.py
frontend/src/model.tsx
frontend/src/old-pages/Users/Users.tsx

This PR removes the `user` group from the authorization model implemented on the backend. Since every user is going to belong to the `admin` group, the Users page now doesn't show the Role column anymore.
- authenticated endpoints only allow `admin`s
- add new users to the `admin` group
- remove Role section from Users page
- remove `set_user_role` endpoint
- manually, by creating new users and checking they are marked as `admin`

Remove user group from authorization model

---

decisions/20221107-adopt-github-labels-to-allow-automating-release-changelog-creation.md
decisions/20221129-adopt-releaselabels-to-automate-changelog-generation.md

This PR adds an ADR to track the decision of adopting release:* labels on our PRs

Add ADR on adopting release:* labels for PRs

---

api/PclusterApiHandler.py
api/tests/test_authenticate.py
api/tests/test_get_identity.py
app.py
frontend/src/components/SideBar.tsx
frontend/src/model.tsx
frontend/src/old-pages/Clusters/Actions.tsx
frontend/src/old-pages/Clusters/Clusters.tsx
frontend/src/old-pages/CustomImages/CustomImages.tsx
frontend/src/pages/index.tsx
frontend/src/store.ts

Following #375, this PR cleans up the codebase removing references to deprecated user and guest roles
- remove distinction between `user` and `admin` from the SideBar
- remove `guest` from the authorized user groups
- fail `get_identity` when no groups for the user are set
- unit tests
- manually by following these steps:
- create a new user via PCM
- logged in with the new user
- created a new cluster successfully
- #375 

Clean up codebase from guest/users roles

---

infrastructure/github-env-setup.yml
infrastructure/pcluster-manager-cognito.yaml
infrastructure/pcluster-manager.yaml

Following #375, this PR removes the user group from Cognito
- remove `CognitoAdminGroup` (please note, the actual group is `user` even though the logical name is `AdminGroup`)
- update `UpdateInfrastructurePolicy` to allow this change to be applied when updating the stack
**Please note**: I decided to not rename the `CognitoUserGroup` because otherwise CFN would conflict as it would temporarily see two groups with the same `groupName: admin`. This should not be a source of confusion in the future, as we only have one user role now and there is no need to distinguish between admins and non-admins
- manually, by updating a stack starting from the latest public release
- via CLI, by assuming the `PrivateInfrastructureUpdateRole` and updating our demo environment 
#375 
In order to increase …

Clean up infrastructure from users role

---

infrastructure/pcluster-manager.yaml

Enable logging of every call made to the API gateway.
**N.B. the demo environment must be recreated from scratch as soon as this PR gets merged.**
- **breaking**: manage manually the stage for the API Gateway so that log settings can be added (it's a breaking change only for stack updates since CloudFormation fails doing that operation)
- add logs settings to the API Gateway stage
- replaced the route matching in place with `$default` as it does exactly what we need to do (match all routes and every method)
Create a new stack and do some manual calls, veryfing the output in the CloudWatch console. …

Enable access logs on the API Gateway

---

frontend/src/components/ErrorBoundary.tsx
frontend/src/components/__tests__/ErrorBoundary.test.tsx
frontend/src/logger/ConsoleLogger.ts
frontend/src/logger/ILogger.ts
frontend/src/logger/LoggerProvider.tsx
frontend/src/logger/RemoteLogger.ts

This PR makes it so the `ILogger` interface can be used without specifying the type of Logger is going to be used under the hood
- remove generic type signature from `ILogger`

Refactor ILogger to remove generic type signature

---

.github/workflows/e2e_tests.yml
infrastructure/github-env-setup.yml
infrastructure/pcluster-manager-cognito.yaml

Creates a new role to execute e2e tests, and setup credentials for the test user with SecretsManager.
E2E credentials are available under the env variables `E2E_TEST1_EMAIL` and `E2E_TEST1_PASSWORD`.
- mimic existing IAM roles to let Github download test user secrets
- don't let external users sign up to the portal: users must be created either on the console or inside the portal directly
Manually run the workflow https://github.com/aws-samples/pcluster-manager/actions/runs/3658679383
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

Setup e2e workflow IAM roles and credentials

---

frontend/locales/en/strings.json
frontend/src/old-pages/Clusters/Properties.tsx
frontend/src/old-pages/Clusters/StackEvents.tsx

Users can easily get to the CloudFormation stack from the Stack Events tab. This PR removes the ugly link and adds in a new SSH command.
* add SSH command
* remove CFN arn
* Include SSH Command in Cluster Summary tab

SSH Command

---

frontend/src/old-pages/Configure/Components.tsx
frontend/src/old-pages/Configure/Storage.tsx

`st1` volumes have a typo (`stl`) preventing the cluster creation.
Created a cluster with an EBS volume of type `st1`: the error about `stl` is now gone

Fix EBS st1 volume type

---

e2e/package-lock.json
e2e/package.json
e2e/playwright.config.ts
e2e/specs/example.spec.ts
e2e/specs/wizard.spec.ts

Following https://github.com/aws-samples/pcluster-manager/pull/387 and https://github.com/aws-samples/pcluster-manager/pull/398, this PR introduces the first e2e test in ParallelCluster Manager. The test performs the following steps:
1. Log into the portal using e2e test account
2. Click on `Create Cluster` button
3. Navigate through the wizard leaving all default options (selecting first VPC only)
4. Perform a dry-run and check that it doesn't fail
Future improvements:
* Retrieve demo environment public URL through Cloudformation
* Leverage Playwright [signed in state](https://playwright.dev/docs/auth) to isolate the login phase. In this way we can log in only once and then skip the log in step for all of the subsequent tests.
* Added first e2e test
* Manually triggered `e2e` workflow on …

Add first e2e test

---

Dockerfile.awslambda
awslambda/entrypoint.py

Removes Lambda powertools from the codebase as it's not strictly needed at this moment. Moreover, the lib raises some Xray issues on Lambda startup and it's one major version behind.
Updated an environment manually and verify that:
- Xray errors have disappeared
- logging is working the same

Remove Lambda powertools

---

.github/workflows/e2e_tests.yml
.github/workflows/gh-pages.yml

Runs e2e tests after each PRs so we can get used to Playwright.
Adds also the ability to publish documentation on-demand, without waiting for a release.

Change e2e and documentation triggers

---

frontend/locales/en/strings.json
frontend/src/auth/__tests__/getCsrfToken.test.ts
frontend/src/auth/getCsrfToken.ts
frontend/src/components/TopBar.tsx
frontend/src/http/__tests__/setCsrfTokenHeader.test.ts
frontend/src/http/setCsrfTokenHeader.ts
frontend/src/model.tsx
frontend/src/pages/index.tsx

This PR implements the Double Submit Cookie strategy on the frontend to prevent CSRF attacks.
- fetch token via `GET /csrf` on application start
- set the `X-CSRF-Token` header for every subsequent request
- unit tests
- manually
- [Double Submit Cookie](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie)

Fetch and send CSRF token on every request

---

e2e/playwright.config.ts
e2e/specs/wizard.spec.ts

The e2e test `wizard.spec.ts` is failing due to the fact that in case the cluster list is empty, two buttons named "Create Cluster" are shown, which leads the `getByRole` locator to resolve to two elements.
This PR aims to solve the disambiguation, by calling `first()` method on the locator before the `click()` operation takes place.
Furthermore, the `actionTimeout` parameter in Playwright config has been increased from 0 to 15s in order to avoid sporadic failures.
* Run `npx playwright test` locally targeting demo environment
* Tested with an empty list
* Tested with a list with 1 cluster …

Fix wizard.spec.ts test to handle the case of an empty cluster list

---

frontend/src/navigation/useLocationChangeLog.ts
frontend/src/navigation/useWizardSectionChangeLog.ts
frontend/src/old-pages/Configure/Configure.tsx
frontend/src/old-pages/Layout.tsx

This PR adds logs when:
- user navigates to another page
- user navigates to another section of the cluster creation wizard
See below screenshot for a sample of the outputs
- add `useLocationChangeLog` to `Layout` component
- add `useWizardSectionChangeLog` to `Configure` component
- manually

Log page navigations and wizard navigations

---

.github/workflows/e2e_tests.yml

This PR introduces a dependency between the `demo_deploy` workflow and the `e2e_tests` workflow
- use `workflow_run` as trigger to e2e_tests workflow
- only run the jobs on success
I haven't

Wait on deployment to demo environment before running e2e

---

frontend/locales/en/strings.json
frontend/src/components/TitleDescriptionHelpPanel.tsx

In the context of aligning PCM with CloudScape help system, this PR introduces a base help panel component to ease the user experience of our customers, providing a way to show helper text for different sections of the product in a cohesive manner.
In subsequent PRs we will gradually remove existing `HelpTooltip` instances in favor of the new help panel.
* Added `TitleDescriptionHelpPanel` to `tools` property of `AppLayout` component in `Layout.tsx` and verified that help panel is displayed correctly 
* https://cloudscape.design/components/help-panel/?tabId=playground
By …

Introduce base help panel

---

e2e/configs/environment.ts
e2e/configs/login.ts
e2e/fixtures/wizard.template.yaml
e2e/specs/wizard.spec.ts
e2e/specs/wizard.template.spec.ts
e2e/test-utils/login.ts
frontend/src/old-pages/Configure/Queues/Queues.tsx
frontend/src/old-pages/Configure/Queues/__tests__/mapComputeResources.test.ts
frontend/src/old-pages/Configure/Queues/queues.mapper.ts
frontend/src/old-pages/Configure/util.tsx

This PR fixes an issue causing the cluster creation wizard to crash whenever a template containing configuration for the single instance type is uploaded
Fixes #366 
- add e2e spec
- add mapper to convert ComputeResources to flexible instance type format
- refactor e2e to centralize config and login steps
Fix cluster creation wizard failing when uploading a template created with the single instance type format (supported untile PC 3.2.0)
- manually, by importing a template and proceeding with the dry run
- e2e spec
- unit tests
By submitting this pull request, I confirm that you …

Safely import ComputeResources config created with single instance type

---

frontend/locales/en/strings.json
frontend/src/components/InfoLink.tsx
frontend/src/components/help-panel/TitleDescriptionHelpPanel.tsx
frontend/src/old-pages/Configure/Components.tsx

Following https://github.com/aws-samples/pcluster-manager/pull/419 and https://github.com/aws-samples/pcluster-manager/pull/420, this PR is the first step towards replacing all instances of `HelpTooltip` with `useHelpPanel()` hook calls in order to be compliant with the CloudScape [help system](https://cloudscape.design/patterns/general/help-system/).
This PR fixes also the link in the footer of `TitleDescriptionHelpPanel` which was not opening a new tab when clicked.
* Manually clicked on new `info` link and verified that help panel is opened and filled as expected
* https://cloudscape.design/examples/react/onboarding.html
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the …

Replace HelpTooltip in custom AMI selection

---

frontend/locales/en/strings.json
frontend/src/components/InfoLink.tsx
frontend/src/components/help-panel/TitleDescriptionHelpPanel.tsx

This PR addresses nitpicks pointed out in https://github.com/aws-samples/pcluster-manager/pull/424:
* Use `type` instead of `interface` for `InfoLinkProps`
* Move external link aria label to a global namespace in i18n strings

Follow-up of #424

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Components.tsx
frontend/src/old-pages/Configure/MultiUser.tsx

This PR adds Info links to MultiUser Properties section (see screenshot below). It's using existing `name` and `help` properties to facilitate the migration
- update `HelpTextInput` component to render `InfoLink` instead of `HelpTooltip`
- add `InfoLink` to Generate SSH keys toggle in MultiUser screen
- remove asterisks from labels, since it's not done anywhere else and it would cause the help panel to show the asterisk as well

Add Info links to MultiUser Properties section

---

frontend/src/components/Status.tsx

This PR removes the help tooltip from the cluster status indicator
- remove HelpTooltip from `ClusterStatusIndicator`

Remove help tooltip from cluster status indicator

---

frontend/locales/en/strings.json
frontend/src/components/InfoLink.tsx
frontend/src/old-pages/Configure/HeadNode.tsx

This PR uses the HelpPanel in the HeadNode section.
- make `ariaLabel` of the `InfoLink` optional since the Info text is always the same
Manually

Replace HelpTooltips with HelpPanel on wizard HeadNode section

---

api/PclusterApiHandler.py

Removed the try-except clause from the delete operation in order to bubble up the real Cognito exception raised so our Boto exception handler can handle it the right way.
- manually
- existing unit tests

Bubble up boto3 Cognito exception for delete user operation

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Storage.tsx

- replaced HelpTooltips with HelpPanel
- replaced custom divs in favor of `FormField`
Manually

Replace HelpTooltip with HelpPanel in storage

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Queues/SingleInstanceComputeResource.tsx

Removed the tooltip and the settings cause it has no effect since PC 3.0.2. From flexible instance types it has been already removed.
https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeResources-Efa-GdrSupport
Manually

Remove HelpTooltip from queues section

---

frontend/locales/en/strings.json
frontend/src/old-pages/Clusters/Accounting.tsx
frontend/src/old-pages/Configure/Components.tsx

This PR uses the HelpPanel in the Accounting tab.
- add copy to `string.json`
- replace `HelpTooltip` with `InfoLink`
manually

Replace HelpTooltips with HelpPanel in Accounting tab

---

frontend/locales/en/strings.json
frontend/src/old-pages/Clusters/Properties.tsx

This PR adopts the HelpPanel in the Details tab (see screenshot below)
- replace `HelpTooltip` with `InfoLink` in `Details` tab
- adopted correct styling for labels done with `Box` (see [here](https://cloudscape.design/examples/react/details-tabs.html))
- manually

Replace HelpTooltips with HelpPanel in Details tab

---

frontend/src/model.tsx

This PR removes the `notify()` call from the error case of the `UpdateCluster` command (same as it had been already done with the `CreateCluster`)
The error is handled via the `errorHandler` which takes care of setting the errors in the store
This also avoid displaying an error Flash message, in case of successful dry run (see screenshot below)
- manually

Remove error notification from the UpdateCluster command

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Queues/SlurmMemorySettings.tsx

Replace a leftover help tooltip with the help panel. 
Manually

Replace help popover with HelpPanel in slurm settings

---

frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
frontend/src/old-pages/Configure/Queues/Queues.tsx
frontend/src/old-pages/Configure/Queues/__tests__/multiAZ.test.tsx

Disable EFA and Placement groups when more than one subnet is select (at the queue level).
Memoize some values in `Queues` and `MultiInstanceComputeResource` to avoid endless renders after the introduction of `useEffect`.
Manually used multi-AZ and verified EFA/PG cannot be enabled

Add validation for multi-AZ and EFA/Placement groups

---

frontend/src/feature-flags/featureFlagsProvider.ts
frontend/src/feature-flags/types.ts
frontend/src/old-pages/Configure/Components.tsx
frontend/src/old-pages/Configure/HeadNode.tsx

With [ParallelCluster 3.4.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.4.0) users are now able to specify a custom script to be executed in the head node during the update of the cluster. The script can be specified with `OnNodeUpdated` parameter when using Slurm as scheduler.
This PR aims at providing support for `OnNodeUpdated` custom action in ParallelCluster Manager, by adding a dedicated component in the advanced options of the HeadNode section of the wizard (see attached image). 
* Added support for `onUpdated` custom action in `HeadNode` section
* Manually tested a dry-run locally using PC API 3.4.0
* Verified that with versions < 3.4.0 the option is not displayed
In order to increase the likelihood of your contribution being accepted, please make sure you have …

Add support for onNodeUpdated custom action in HeadNode

---

api/tests/test_push_log.py
app.py

Improved /logs endpoint expected json schema
Right now the `/logs` endpoint accepts a json containing a single key `logs` with a list of log entries, like this
```javascript
{
'logs': [
{ 
'message': 'sample-message',
'level': 'info',
'extra': { ... }
}
]
}
```
- manual
- unit tests
- [] I added tests to new or existing code

Improved /logs endpoint expected json schema

---

frontend/src/logger/RemoteLogger.ts
frontend/src/logger/__tests__/logger.test.ts

Introduces a buffering logic when sending logs from the client to the server. Logs are sent to the server when 20 logs have been collected or after 5 seconds.
Locally by using the portal and verified that logs are sent in chunks

Buffer logs sent from the frontend

---

api/PclusterApiHandler.py
api/tests/test_logout.py

Added Cognito logout implementation as part of the PCM logout process.
This PR refactors the previous logout implementation adding the proper redirection to Cognito logout endpoint to allow a user to logout properly and have the chance to login as a different user if needed.
- manually
- unit tests
- e2e tests

Added Cognito logout implementation

---

frontend/locales/en/strings.json
frontend/src/feature-flags/featureFlagsProvider.ts
frontend/src/feature-flags/types.ts
frontend/src/old-pages/Configure/Components.tsx
frontend/src/old-pages/Configure/Queues/Queues.test.tsx
frontend/src/old-pages/Configure/Queues/Queues.tsx
frontend/src/old-pages/Configure/Queues/SubnetMultiSelect.tsx
frontend/src/old-pages/Configure/Queues/__tests__/SubnetMultiSelect.test.tsx
frontend/src/old-pages/Configure/Queues/queues.types.ts
frontend/src/old-pages/Configure/util.tsx

With [ParallelCluster 3.4.0](https://github.com/aws/aws-parallelcluster/releases), customers are able to launch nodes across multiple availability zones, in order to increase capacity availability for their clusters.
This PR aims at adding support for Multi-AZ feature in ParallelCluster Manager.
If the deployed version of PC API is < `3.4.0`, a single `Select` component is displayed in the subnet selection section in the `Queues` page. If PC API version >= `3.4.0` a `MultiSelect` component is displayed instead (see attached images). In this way, users are able to specify multiple subnets in different availability zones.
* Added support for Multi-AZ
* Unit tests
* Manual tests with `3.3.0` and `3.4.0` versions
* https://cloudscape.design/components/multiselect/
* …

Add support for Multi-AZ

---

api/PclusterApiHandler.py

Switched to exception handler based handling of errors inside `get_cluster_config` operation.
- unit tests

Avoid returning AWS IAM error as-is

---

frontend/locales/en/strings.json

In `Slurm Settings` section of `Head Node` step of the wizard, users need to submit a password arn in the `Password` field.
Labeling it just with `Password` may lead to confusion.
* Renamed `Password` field label in Slurm settings to `Password Secret Arn` to avoid confusion
* Manually inspected Slurm settings section (see attached image)

Rename 'Password' field label in Slurm settings to 'Password Secret Arn'

---

frontend/src/components/TopBar.tsx
frontend/src/components/__tests__/TopBar.test.tsx

Fixes a bug where an error message was flashed after switching the region.
- Selected a cluster, changed the region and verified to error message appears

Clear selected cluster when the region is changed

---

frontend/package-lock.json
frontend/src/old-pages/Clusters/Clusters.tsx
frontend/src/old-pages/CustomImages/CustomImages.tsx
frontend/src/old-pages/OfficialImages/OfficialImages.tsx
frontend/src/old-pages/Users/Users.tsx

Updates Cloudscape after fixing the following issue https://github.com/cloudscape-design/components/issues/459
- Cloudscape version bump
- introduce sticky headers on the lists, now working after the fix
Tried the clusters list with 4 clusters and the scrollbar is not shown

Fix scrollbar in lists and use sticky headers

---

infrastructure/pcluster-manager.yaml

This PR adds support for setting up a new deployment of PCM without deploying a new Cognito user pool instance, so that a previously deployed user pool could be used instead.
This is achieved through the use of new parameters (easily obtainable from CloudFormation console) to be passed at stack creation time.
- Introduced external cognito parameters
- adjusted parameter descriptions
- manual tests on multiple deployments on my personal account
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Added support for configuring existing PCM-deployed Cognito user pool with a new PCM installation

---

infrastructure/pcluster-manager-cognito.yaml
infrastructure/pcluster-manager.yaml

PCM main stack has been refactored to only handle PCM specific logic and to allow external Cognito configuration.
- manually on my personal account numerous times
#456 

Allow for PCM and Cognito stacks to be deployed separately

---

e2e/specs/wizard.spec.ts
e2e/specs/wizard.template.spec.ts
frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Cluster.tsx
frontend/src/old-pages/Configure/Configure.tsx
frontend/src/old-pages/Configure/Create.tsx
frontend/src/old-pages/Configure/HeadNode.tsx
frontend/src/old-pages/Configure/MultiUser.tsx
frontend/src/old-pages/Configure/Storage.tsx
frontend/src/old-pages/Configure/__tests__/useWizardNavigation.test.tsx
frontend/src/old-pages/Configure/useWizardNavigation.ts

This PR introduces the CloudScape [Wizard](https://cloudscape.design/components/wizard/?tabId=playground) component in the create cluster wizard.
* Adopted CloudScape Wizard component in the create cluster wizard
* Created new cluster
* Navigated through wizard (next, back, select step)
* Enable/disable MultiUser and verified that navigation works as expected
* Dry-run successful
* Updated existing cluster
* Verified options are loaded and validated correctly 
* Dry-run successful
* https://cloudscape.design/components/wizard/
By submitting this pull request, I confirm that you …

Adopt CloudScape Wizard component

---

api/PclusterApiHandler.py
api/exception/exceptions.py
api/exception/handlers.py
api/pcm_globals.py
api/tests/exceptions/test_exception_handlers.py
api/tests/test_authenticate.py
infrastructure/pcluster-manager.yaml

This PR introduces the implementation of the refresh token flow for the OAuth2 protocol, enabling us to shorten token lifespans without breaking user experience.
- the `authenticate` method now checks if it's possible to refresh tokens when an expired accesstoken is used, and if so it performs the refresh setting new cookies values to be added to the response in a request context ( `g.auth_cookies`) to be used in a custom `afterresponse` func (this was done to avoid handling response objects manually since a view function could return either a dict and a code like in `app.py`, or a true `Response` object, like in `handlers.py`)
- added custom refreshtokenerror exception + handler
- tests have been added and existing tests adjusted
- edited the pcluster-manager.yaml to shorten lifespans of …

Added OAuth2 refresh token flow implementation + shortened `id` and `access` token lifespans

---

infrastructure/pcluster-manager.yaml

By default API Gateway has large throttling limits: this change ensures a reasonable limit is used instead.
- created a new env and verified a user don't get throttled with those limits

Limit invocations on API Gateway routes

---

e2e/specs/wizard.spec.ts
e2e/specs/wizard.template.spec.ts

Fix e2e tests broken due to https://github.com/aws-samples/pcluster-manager/pull/465.
* `npx playwright test` executed successfully against local and demo environment
* https://github.com/aws-samples/pcluster-manager/pull/465

Fix e2e tests broken after #465

---

api/validation/schemas.py
api/validation/validators.py
app.py

This PR introduces custom validators for the following endpoints:
* `/manager/get_cluster_configuration`
* `/manager/get_custom_image_configuration`
* `/manager/get_aws_configuration`
* `/manager/get_instance_types`
* Added input validators for the following endpoints: get_cluster_configuration, get_custom_image_configuration, get_aws_configuration, get_instance_types
* Manual tests on local environment with Postman
* https://marshmallow.readthedocs.io/en/stable/marshmallow.validate.html
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

Add endpoints validators

---

frontend/src/old-pages/Clusters/Filesystems.tsx
frontend/src/old-pages/Clusters/__tests__/Filesystems.test.ts

This PR fixes an issue causing the Storage tab to crash the app when the filesystem is not ready yet. 
The root cause was the construction of link to the filesystem, which depends on the head node information to be available. More precisely, the `headNode.instanceId` property access cases an error due to the `headNode` being undefined. 
The fix is as follows:
- until the headnode is not available, the filesystem is listed without the link to the console
- when the headnode is available, the link is correctly shown
See screenshots below:
Link not available due to missing information:
Link available:
- add `buildFilesystemLink` function to create the link
- avoid displaying a `<Link/>`, when the href is missing
Fix storage tab crashing when headnode is not available yet
- manually
- unit …

Fix storage tab crashing when headnode is not available yet

---

api/security/csrf/__init__.py
api/tests/security/csrf/test_csrf.py

This PR slightly changes the implementation of the get csrf token endpoint to return the already present csrf token if there's one.

Allow multiple tabs by not creating a new csrf token if one is already present

---

api/PclusterApiHandler.py
api/tests/test_get_identity.py

Removed 401 from get_identity + adjusted tests
- manual
- unit tests

Fixed get_identity causing full login processes

---

api/PclusterApiHandler.py
api/validation/schemas.py
app.py
requirements.txt

This PR introduces the only missing endpoint validation (the PC API proxy) and switches away from the flask-restful approach for defining resources. This was done because this dependency was only needed for two locations in the code and doesn't bring any value to project at the moment.
- manually, by triggering post, delete and get operations on the PC API
- unit tests
- e2e

Added validation for PC API proxy + removed Flask-RESTful and adapted code

---

DEVELOPMENT.md
README.md
decisions/index.md
e2e/specs/wizard.spec.ts
frontend/locales/en/strings.json
frontend/package-lock.json
frontend/package.json
frontend/src/components/TopBar.tsx
frontend/src/pages/_app.tsx
frontend/src/pages/_document.tsx

This PR replaces all the customer-facing occurrences of `ParallelCluster Manager`, `pcluster-manager` or `PCM` with the new product name: `AWS ParallelCluster UI`.
Project name in `package.json` and `package-lock.json` has been renamed to `aws-parallelcluster-ui` following npm [naming conventions](https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields).
* Rename customer-facing occurrences of `ParallelCluster Manager` with `AWS ParallelCluster UI`
* unit tests
* manually checked that new name is displayed
* https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the …

Replace occurrences of 'ParallelCluster Manager' with 'AWS ParallelCluster UI'

---

frontend/src/components/ErrorBoundary.tsx
frontend/src/components/__tests__/ErrorBoundary.test.tsx

This PR adds stacktraces to the log entries coming off the `ErrorBoundary`
- log `stacktrace` and `componentStack` for errors occurring during component rendering
- log `stacktrace` for uncaught errors occurring elsewhere
<details>
<summary>Logs for errors occurring during component rendering</summary>
</details>
<details>
<summary>Logs for uncaught errors occurring elsewhere</summary>
</details>
- manually
- unit tests
- deployed and checked on CloudWatch (see screenshots above)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Log stacktraces in ErrorBoundary

---

api/PclusterApiHandler.py

Small fix to align tokens values with refreshed ones.
Previously this would cause a failure in get_identity function due to an expired id_token.
- manual
- unit
- e2e

Align id and access tokens value in `get_identity` after refresh flow

---

api/exception/handlers.py
api/security/csrf/csrf.py
api/tests/exceptions/test_exception_handlers.py
api/tests/security/csrf/conftest.py

This PR takes care of three things:
- switches to sha256 for the strategy used when creating a CSRF token
- in case of a CSRF token error the cookie gets deleted
- tests are adjusted and added for csrf exception handler
- unit tests
- e2e
- manual tests running "state changing" requests that trigger the csrf token check

Adopted sha256 for CSRF token generation and improved CSRFError handler + tests

---

api/tests/exceptions/test_exception_handlers.py

This PR refactors existing tests for exception handlers to not rely on existing endpoints to be invoked.
- unit tests
- follow up to #488 
- [] I checked that `npm run build` builds without any error

Improved exception handler tests

---

frontend/src/components/ErrorBoundary.tsx
frontend/src/components/__tests__/ErrorBoundary.test.tsx
frontend/src/logger/ConsoleLogger.ts
frontend/src/logger/ILogger.ts
frontend/src/logger/RemoteLogger.ts
frontend/src/logger/__tests__/logger.test.ts

This PR fixes an issue allowing any payload to be sent as message to the remote logging system. 
This is mostly related to the fact that rejected promises can contain any value, thus by blindly logging the `event.reason` of the `PromiseRejectionEvent` we risk to push non-string values to the remote logging system
This could also occur in the future, by logging values that have been typed as `any` (which would defeat the type checking), therefore the guard is place inside the `RemoteLogger`
- log stacktraces when Errors are logged
- stringify non-string messages before pushing them
- handle undefined messages
- manually
- unit tests
Log entry to be sent to the remote logging system, in case of an uncaught axios error:
In order to increase the likelihood of your contribution being accepted, …

Fix logger pushing non-string payloads to remote logging system

---

api/utils.py
app.py
e2e/specs/noMatch.spec.ts
frontend/locales/en/strings.json
frontend/public/img/error_pages_illustration.svg
frontend/src/components/NoMatch.tsx
frontend/src/components/help-panel/TitleDescriptionHelpPanel.tsx
frontend/src/old-pages/Layout.tsx
frontend/src/pages/index.tsx

Currently, pointing to a non-existing page in PCUI returns an empty page, which can be confusing for customers.
This PR introduces a new error page template in PCUI that displays a clear message to the user indicating that an error has occurred, along with options for resolving the issue.
* Add error page to be displayed if an unmatched route is hit
* Manual tests navigating to unmatched routes, even in the case where the frontend is served by the backend
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Display error page in case an unmatched route is hit

---

api/security/fingerprint.py
api/tests/conftest.py
api/tests/security/test_secret_generator.py

Replace a custom made hash function with pbkdf2_hmac to generate the fingerprint used in the CSRF token generation.
Tested a local version of the frontend with auth enabled, and verified that mutations work seamlessly.

Use pbkdf2_hmac in fingerprint generation

---

DEVELOPMENT.md
api/tests/conftest.py
api/tests/test_authenticate.py
api/tests/test_get_identity.py
api/tests/test_push_log.py
api/tests/validation/test_api_validation.py
api/utils.py
infrastructure/pcluster-manager.yaml

This PR removes the possibility of disabling the authentication by changing a CloudFormation parameter.
In order to protect customers from affecting the security of their installation, this PR also removes the possibility of disabling the authentication by changing an environment variable passed to the Lambda
- remove `EnableAuth` CloudFormation parameter
- remove `ENABLE_AUTH` environment variable
- ran unit and e2e tests
- set the environment variable and checked that the auth does not get disabled
- tested that you can still disable authentication when developing locally
- verified the Stack Create screen does not allow to configure the EnableAuth anymore (see screenshot below)
- set the environment variable in the Lambda Console and checked that auth does not get disabled
In order to …

Remove EnableAuth parameter to configure the authentication

---

api/security/csrf/__init__.py
api/security/csrf/csrf.py
api/tests/security/csrf/conftest.py
api/tests/security/csrf/test_csrf.py

This PR changes the way CSRF token (and cookie) are generated, moving from a `URLSafeSerializer` to a `URLSafeTimedSerializer`.
Now CSRF tokens are valid for 30 seconds, after that they would throw bad signature exception.
Now invocation of the `/csrf` token always returns (and sets as an expiring cookie) a new token.
- unit tests
- e2e
- manual tests

Improved CSRF token handling with TimedSignature

---

frontend/src/http/__tests__/executeRequest.test.ts
frontend/src/http/executeRequest.tsx

Sending a customer header to a DELETE request doesn't work after the introduction of #496.

Forward custom headers correctly in DELETE requests

---

frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
frontend/src/feature-flags/featureFlagsProvider.ts
frontend/src/feature-flags/types.ts
frontend/src/old-pages/Configure/Storage.tsx
frontend/src/old-pages/Configure/__tests__/dynamicFS.test.tsx

Add support for PCluster 3.3.0 [filesystems mount during updates](https://docs.aws.amazon.com/parallelcluster/latest/ug/document_history.html#aws-parallelcluster-3.3.0).
- created a cluster
- while editing the newly created cluster a new shared storage has been created
- dry run passes

Support for dynamic filesystems mount

---

infrastructure/github-env-setup.yml
infrastructure/parallelcluster-ui-cognito.yaml
infrastructure/parallelcluster-ui.yaml
infrastructure/readme.md
infrastructure/update-environment-infra.sh
scripts/update.sh

This PR aims to replace occurrences of PCM / PclusterManager / ParallelClusterManager with "ParallelCluster UI" and rename files accordingly.
* `pcluster-manager.yaml` -> `parallelcluster-ui.yaml`
* `pcluster-manager-cognito.yaml` -> `parallecluster-ui-cognito.yaml`
* In some resources the `PclusterManager` prefix has been removed since considered not useful. All resources created will still have the stack name as prefix.
* Successfully deployed stacks on my personal account
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Replace occurrences of PCM with PCUI and rename files accordingly

---

frontend/locales/en/strings.json
frontend/src/old-pages/Clusters/Clusters.tsx
frontend/src/old-pages/Clusters/Properties.tsx

This PR removes hardcoded strings and adjust copywriting for clusters list page following the suggestions of our copywriter.
* Manually tested locally

Adjust copywriting for clusters list page

---

frontend/locales/en/strings.json
frontend/src/old-pages/Clusters/Accounting.tsx
frontend/src/old-pages/Clusters/Details.tsx
frontend/src/old-pages/Clusters/Filesystems.tsx
frontend/src/old-pages/Clusters/Instances.tsx
frontend/src/old-pages/Clusters/Logs.tsx
frontend/src/old-pages/Clusters/Scheduling.tsx

This PR removes hardcoded strings and adjust copywriting for cluster details page following the suggestions of our copywriter.
* Manually tested locally

Adjust copywriting for cluster details page

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Components.tsx
frontend/src/old-pages/Configure/HeadNode.tsx
frontend/src/old-pages/Configure/SlurmSettings/QueueUpdateStrategyForm.tsx
frontend/src/old-pages/Configure/SlurmSettings/ScaledownIdleTimeForm.tsx
frontend/src/old-pages/Configure/SlurmSettings/SlurmAccountingForm.tsx
frontend/src/old-pages/Configure/SlurmSettings/SlurmSettings.tsx

This PR removes hardcoded strings and adjust copywriting for wizard head node page following the suggestions of our copywriter.
* Manually tested locally

Adjust copywriting for wizard head node page

---

.github/workflows/production_release.yml
decisions/20230125-pcui-versioning-strategy.md
infrastructure/parallelcluster-ui.yaml
scripts/build_and_release_image.sh

This PR adopts the new PC UI versioning strategy and removes useless code + adds an ADR about it.
- first I tested the validation on inputs and outcomes of possible valid/not valid inputs without producing images
- then I only changed the ecr public registry to my personal account public registry, and ran the script as is, verifying it works

Changed versioning strategy for PC UI + ADR

---

infrastructure/parallelcluster-ui.yaml

Fixed ecr image recipe version after newly introduced versioning strategy for PC UI
- introduced a new entry in ParallelClusterUI mapping in main CF template, to handle the ecr image recipe version that needs to be a sem ver like value.
- #513 

Fixed ecr image recipe version after newly introduced versioning strategy for PC UI

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Components.tsx
frontend/src/old-pages/Configure/HeadNode.tsx
frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
frontend/src/old-pages/Configure/Queues/Queues.tsx
frontend/src/old-pages/Configure/Queues/SingleInstanceComputeResource.tsx

This PR removes hardcoded strings and adjust copywriting for wizard queues page following the suggestions of our copywriter.
* Manually tested locally

Adjust copywriting for wizard queues page

---

frontend/locales/en/strings.json
frontend/src/components/help-panel/TitleDescriptionHelpPanel.tsx
frontend/src/old-pages/Clusters/Clusters.tsx
frontend/src/old-pages/Clusters/Properties.tsx
frontend/src/old-pages/Clusters/__tests__/Clusters.test.tsx

Guide users through the application with the help of Cloudscape Help Panel.
- [override Help Panel footer links](https://github.com/aws-samples/pcluster-manager/commit/17bc8a642cb44028fdd3e0fbaced7b0f1283626a)
- add help panel for the clusters list
- slightly modify the EC2 instance connect help panel
https://cloudscape.design/patterns/general/help-system/

Clusters list help panel

---

frontend/src/old-pages/Configure/Cluster.tsx
frontend/src/old-pages/Configure/Components.tsx
frontend/src/old-pages/Configure/Create.tsx
frontend/src/old-pages/Configure/HeadNode.tsx
frontend/src/old-pages/Configure/MultiUser.tsx
frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
frontend/src/old-pages/Configure/Queues/Queues.tsx
frontend/src/old-pages/Configure/Queues/SingleInstanceComputeResource.tsx
frontend/src/old-pages/Configure/Queues/SlurmMemorySettings.tsx
frontend/src/old-pages/Configure/Storage.tsx

Replaced Toggle with Checkbox instances everywhere in the wizard
* https://cloudscape.design/components/checkbox/

Replace Toggle with Checkbox instances everywhere in the wizard

---

frontend/locales/en/strings.json
frontend/src/old-pages/Clusters/Instances.tsx

* Moved actions in header section in cluster instances tab
* Added i18n strings
* Manuallt on local environment
* https://cloudscape.design/components/header/?tabId=playground

Move actions in header section in cluster instances tab

---

frontend/locales/en/strings.json
frontend/src/components/help-panel/TitleDescriptionHelpPanel.tsx
frontend/src/old-pages/CustomImages/CustomImages.tsx

This PR adds the help panel content for the Custom Images page
It builds on #521 
- manually

Add HelpPanel to Custom Images page

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Cluster.tsx
frontend/src/old-pages/Configure/Configure.tsx

Add the Cloudscape Help Panel in the cluster properties step of the wizard.

Add help panel for wizard cluster properties

---

frontend/locales/en/strings.json
frontend/src/old-pages/Clusters/Properties.tsx

Replaced view configuration `<Button>` with a `<Link>`
* https://cloudscape.design/components/link/?tabId=playground&example=secondary-link

Replace view configuration button with a link

---

e2e/specs/wizard.template.spec.ts
frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Source.tsx

This PR adds the help panel content for the Source step of the cluster wizard.
This PR also fixes a small change in a e2e test.
It builds on #521 
- manually
- e2e tests
- [] I added tests to new or existing code

Add HelpPanel to Source step of the cluster wizard + fix e2e

---

api/PclusterApiHandler.py
frontend/src/model.tsx
frontend/src/old-pages/Users/Users.tsx
infrastructure/parallelcluster-ui-cognito.yaml
infrastructure/parallelcluster-ui.yaml

* This commit removes two old parameters `EnableMFA`, and `AdminUserPhone` that were used for SMS based MFA. Instead of this we advise users to setup MFA using an authenticator app following the instructions [here](https://pcluster.cloud/02-tutorials/01-setup-mfa.html).
* Remove parameters, `EnableMFA`, and `AdminUserPhone` from CloudFormation stack.
* Remove parameters, `EnableMFA`, and `AdminUserPhone` from CloudFormation stack.
TBD - wasn't sure how to test changes to the container image.
* https://pcluster.cloud/02-tutorials/01-setup-mfa.html …

Remove SMS and MFA Parameters

---

frontend/locales/en/strings.json
frontend/src/old-pages/CustomImages/CustomImageDetails.tsx
frontend/src/types/images.tsx

Use `<Table>` component in custom images tags tab
* https://cloudscape.design/components/table/

Use Table component in custom images tags tab

---

frontend/locales/en/strings.json
frontend/src/components/InfoLink.tsx
frontend/src/components/help-panel/HelpPanel.tsx
frontend/src/components/help-panel/TitleDescriptionHelpPanel.tsx
frontend/src/old-pages/Configure/Configure.tsx
frontend/src/old-pages/Configure/HeadNode.tsx
frontend/src/old-pages/Configure/SlurmSettings/SlurmSettings.tsx
frontend/src/old-pages/Layout.tsx

Add Cloudscape Help Panels to the Head node section of the wizard.
- add main Head node help panel
- add Slurm settings help panel
- fix a bug causing a wrong re-render of the help panel inside the wizard
Verified that the right help panels appear during the wizard

Head node help panels

---

frontend/locales/en/strings.json
frontend/src/old-pages/Users/Users.tsx

This PR adds the help panel content for the Users page
It builds on #521 
- manually

Add HelpPanel to Users page

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Configure.tsx
frontend/src/old-pages/Configure/Create.tsx

This PR adds the help panel content for the Create or Edit review page
- manually

Add HelpPanel to Create or Edit review page

---

frontend/locales/en/strings.json
frontend/src/old-pages/OfficialImages/OfficialImages.tsx

This PR adds the help panel content for the Official Images page
It builds on #521 
- manually

Add HelpPanel to Official Images page

---

frontend/src/old-pages/CustomImages/CustomImageDetails.tsx

Use copy `Buttons` in custom images properties tab
* https://cloudscape.design/components/copy-to-clipboard/

Use inline copy buttons in custom images properties tab

---

e2e/specs/wizard.spec.ts
e2e/specs/wizard.template.spec.ts

This PR fixes e2e tests, failing after #537 

Fix e2e tests

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Configure.tsx
frontend/src/old-pages/Configure/Queues/Queues.tsx
frontend/src/old-pages/Configure/Queues/SlurmMemorySettings.tsx

Add Cloudscape Help Panels inside the Queues page of the wizard.

Add Queues help panels

---

frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Source.tsx
frontend/src/old-pages/Configure/__tests__/useWizardNavigation.test.tsx
frontend/src/old-pages/Configure/useWizardNavigation.ts

This PR removes the possibility of creating a cluster by uploading a file
- remove file upload from the options of the radio group
- remove wizard navigation special case related to the file upload user flow
- unit tests
- e2e tests locally
- manually, see screenshot

Remove File Upload as a way to create clusters

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/date/AbsoluteTimestamp.tsx
frontend/src/components/date/DateView.tsx
frontend/src/components/date/__tests__/DateView.test.tsx
frontend/src/old-pages/Clusters/Instances.tsx
frontend/src/old-pages/Clusters/Properties.tsx
frontend/src/old-pages/Clusters/StackEvents.tsx
frontend/src/old-pages/CustomImages/CustomImageDetails.tsx
frontend/src/old-pages/CustomImages/CustomImageStackEvents.tsx
frontend/src/old-pages/Users/Users.tsx

* Add `AbsoluteTimestamp` component to display dates following Cloudscape guidelines
* https://cloudscape.design/patterns/general/timestamps/

Add AbsoluteTimestamp component to display dates following Cloudscape guidelines

---

e2e/specs/wizard.spec.ts
e2e/specs/wizard.template.spec.ts
frontend/locales/en/strings.json
frontend/src/old-pages/Configure/Configure.tsx
frontend/src/old-pages/Configure/Storage.tsx

This PR adds the info help panel for the storage session.
- manually
- unit tests
- e2e

Added storage section help panel

---

frontend/locales/en/strings.json
frontend/src/components/TopBar.tsx

This PR fixes an issue, making the logout button linking to non-existing pages, instead of properly logging out the user.
- make the signout link to be relative to the domain instead of relative to the current path
- add i18n strings
- manually
- [Cloudscape documentation](https://cloudscape.design/components/button-dropdown/?tabId=playground)

Fix sign out not working when a cluster is selected

---

frontend/src/old-pages/Configure/Cluster.tsx
frontend/src/old-pages/Configure/__tests__/itemToOption.test.ts

This PR  fixes a bug with the OS select dropdown which showed the dropdown option label and value as a concatenated string.
It also switches to a formfield wrapping the select for consistency with the rest of the wizard, also fixing a layout issue where the select would adapt to the width of the current selection, forcingly wrapping other option strings when the dropdown was open.
- improved and typed `itemToOption` funcion + added test for it
- switched to FormField wrapping a Select for OS, Vpc and Region selection in second step of the wizard
- unit tests
- e2e tests
- manual testing
- [] I removed hardcoded strings and used our `i18n` solution instead (see [here](https://github.com/aws-samples/pcluster-manager/pull/175/commits/fdc6b77987c87a26f51dbc8da5d371d95ef80601))
In order to …

Fixed OS select dropdown + switched to FormField for consistency with the rest of wizard
